// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2024 AIROHA Inc
 * Author: Christian Marangi <ansuelsmth@gmail.com>
 */
#include <linux/math.h>
#include <linux/phy/phy.h>
#include <linux/phylink.h>
#include <linux/regmap.h>

#include "pcs-airoha.h"

#include <linux/of.h>

enum {
	AN7581_PCS_CMN_EN,

	AN7581_PCS_JCPLL_SPARE_L,
	AN7581_PCS_JCPLL_RST_DLY,
	AN7581_PCS_JCPLL_PLL_RSTB,
	AN7581_PCS_JCPLL_SDM_DI_EN,
	AN7581_PCS_JCPLL_SDM_DI_LS,

	AN7581_PCS_JCPLL_SDM_OUT,
	AN7581_PCS_JCPLL_SDM_ORD,
	AN7581_PCS_JCPLL_SDM_MODE,
	AN7581_PCS_JCPLL_SDM_IFM,
	AN7581_PCS_JCPLL_SDM_HREN,

	AN7581_PCS_JCPLL_CHP_IOFST,
	AN7581_PCS_JCPLL_CHP_IBIAS,
	AN7581_PCS_JCPLL_LPF_SHCK_EN,

	AN7581_PCS_JCPLL_LPF_BWR,
	AN7581_PCS_JCPLL_LPF_BP,
	AN7581_PCS_JCPLL_LPF_BC,
	AN7581_PCS_JCPLL_LPF_BR,
	AN7581_PCS_JCPLL_LPF_BWC,

	AN7581_PCS_JCPLL_VCO_SCAPWR,
	AN7581_PCS_JCPLL_VCO_HALFLSB_EN,
	AN7581_PCS_JCPLL_VCO_CFIX,
	AN7581_PCS_JCPLL_VCODIV,
	AN7581_PCS_JCPLL_VCO_VCOVAR_BIAS_L,
	AN7581_PCS_JCPLL_VCO_VCOVAR_BIAS_H,
	AN7581_PCS_JCPLL_VCO_TCLVAR,

	AN7581_PCS_JCPLL_POSTDIV_D5,
	AN7581_PCS_JCPLL_MMD_PREDIV_MODE,

	AN7581_PCS_JCPLL_KBAND_KS,
	AN7581_PCS_JCPLL_KBAND_KF,
	AN7581_PCS_JCPLL_KBAND_KFC,
	AN7581_PCS_JCPLL_KBAND_DIV,
	AN7581_PCS_JCPLL_KBAND_CODE,
	AN7581_PCS_JCPLL_KBAND_OPTION,

	AN7581_PCS_JCPLL_TCL_AMP_VREF,
	AN7581_PCS_JCPLL_TCL_AMP_GAIN,
	AN7581_PCS_JCPLL_TCL_AMP_EN,

	AN7581_PCS_JCPLL_TCL_LPF_BW,
	AN7581_PCS_JCPLL_TCL_LPF_EN,

	AN7581_PCS_JCPLL_SSC_DELTA,
	AN7581_PCS_JCPLL_SSC_DELTA1,
	AN7581_PCS_JCPLL_SSC_PERIOD,
	AN7581_PCS_JCPLL_SSC_TRI_EN,
	AN7581_PCS_JCPLL_SSC_EN,
	AN7581_PCS_JCPLL_SSC_PHASE_INI,
	AN7581_PCS_JCPLL_TCL_KBAND_VREF,

	AN7581_PCS_TXPLL_LDO_VCO_OUT,
	AN7581_PCS_TXPLL_LDO_OUT,
	AN7581_PCS_TXPLL_PLL_RSTB,
	AN7581_PCS_TXPLL_RST_DLY,
	AN7581_PCS_TXPLL_REFIN_DIV,
	AN7581_PCS_TXPLL_REFIN_INTERNAL,
	AN7581_PCS_TXPLL_SDM_MODE,
	AN7581_PCS_TXPLL_SDM_IFM,
	AN7581_PCS_TXPLL_SDM_DI_LS,
	AN7581_PCS_TXPLL_SDM_DI_EN,
	AN7581_PCS_TXPLL_SDM_HREN,
	AN7581_PCS_TXPLL_SDM_ORD,
	AN7581_PCS_TXPLL_SDM_OUT,
	AN7581_PCS_TXPLL_SSC_DELTA1,
	AN7581_PCS_TXPLL_SSC_DELTA,
	AN7581_PCS_TXPLL_SSC_TRI_EN,
	AN7581_PCS_TXPLL_SSC_PHASE_INI,
	AN7581_PCS_TXPLL_SSC_EN,
	AN7581_PCS_TXPLL_SSC_PERIOD,
	AN7581_PCS_TXPLL_LPF_BC,
	AN7581_PCS_TXPLL_LPF_BR,
	AN7581_PCS_TXPLL_LPF_BP,
	AN7581_PCS_TXPLL_LPF_BWC,
	AN7581_PCS_TXPLL_LPF_BWR,
	AN7581_PCS_TXPLL_CHP_IOFST,
	AN7581_PCS_TXPLL_CHP_IBIAS,
	AN7581_PCS_TXPLL_VCO_CFIX,
	AN7581_PCS_TXPLL_VCO_VCOVAR_BIAS_L,
	AN7581_PCS_TXPLL_VCO_VCOVAR_BIAS_H,
	AN7581_PCS_TXPLL_VCO_TCLVAR,
	AN7581_PCS_TXPLL_VCO_SCAPWR,
	AN7581_PCS_TXPLL_VCO_HALFLSB_EN,
	AN7581_PCS_TXPLL_KBAND_CODE,
	AN7581_PCS_TXPLL_KBAND_OPTION,
	AN7581_PCS_TXPLL_KBAND_KS,
	AN7581_PCS_TXPLL_KBAND_KF,
	AN7581_PCS_TXPLL_KBAND_KFC,
	AN7581_PCS_TXPLL_KBAND_DIV,
	AN7581_PCS_TXPLL_MMD_PREDIV_MODE,
	AN7581_PCS_TXPLL_POSTDIV_EN,
	AN7581_PCS_TXPLL_VCODIV,
	AN7581_PCS_TXPLL_TCL_KBAND_VREF,
	AN7581_PCS_TXPLL_TCL_AMP_GAIN,
	AN7581_PCS_TXPLL_TCL_AMP_VREF,
	AN7581_PCS_TXPLL_TCL_LPF_BW,
	AN7581_PCS_TXPLL_TCL_LPF_EN,
	AN7581_PCS_TXPLL_TCL_AMP_EN,

	AN7581_PCS_TX_DMEDGEGEN_EN,
	AN7581_PCS_TX_CKLDO_EN,

	AN7581_PCS_RX_DAC_EYE_BYPASS_AEQ,
	AN7581_PCS_RX_DAC_E1_BYPASS_AEQ,
	AN7581_PCS_RX_DAC_E0_BYPASS_AEQ,
	AN7581_PCS_RX_DAC_D1_BYPASS_AEQ,
	AN7581_PCS_RX_DAC_D0_BYPASS_AEQ,
	AN7581_PCS_RX_FE_VCM_GEN_PWDB,
	AN7581_PCS_RX_OSCAL_FORCE,
	AN7581_PCS_RX_DAC_MON,
	AN7581_PCS_RX_REV_1_FE_BUF1_BIAS_CTRL,
	AN7581_PCS_RX_REV_1_FE_BUF2_BIAS_CTRL,
	AN7581_PCS_RX_REV_1_SIGDET_ILEAK,
	AN7581_PCS_RX_FE_VB_EQ3_EN,
	AN7581_PCS_RX_FE_VB_EQ2_EN,
	AN7581_PCS_RX_FE_VB_EQ1_EN,
	AN7581_PCS_RX_FE_EQ_HZEN,
	AN7581_PCS_RX_SIGDET_VTH_SEL,
	AN7581_PCS_RX_SIGDET_PEAK,
	AN7581_PCS_RX_SIGDET_LPF_CTRL,
	AN7581_PCS_RX_TDC_CK_SEL,
	AN7581_PCS_RX_PHYCK_RSTB,
	AN7581_PCS_RX_PHYCK_SEL,
	AN7581_PCS_RX_PHYCK_DIV,
	AN7581_PCS_RX_PHY_CK_SEL_FORCE,
	AN7581_PCS_RX_PHY_CK_SEL,

	AN7581_PCS_AEQ_OFORCE,

	AN7581_PCS_CDR_PD_EDGE_DIS,
	AN7581_PCS_CDR_PD_PICAL_CKD8_INV,

	AN7581_PCS_CDR_PR_XFICK_EN,
	AN7581_PCS_CDR_PR_MONPI_EN,
	AN7581_PCS_CDR_PR_MONPR_EN,
	AN7581_PCS_CDR_PR_KBAND_DIV,
	AN7581_PCS_CDR_PR_BETA_SEL,
	AN7581_PCS_CDR_PR_VCOADC_OS,
	AN7581_PCS_CDR_PR_BETA_DAC,
	AN7581_PCS_CDR_PR_FBKSEL,
	AN7581_PCS_CDR_PR_DAC_BAND,
	AN7581_PCS_CDR_PR_VREG_CKBUF_VAL,
	AN7581_PCS_CDR_PR_VREG_IBAND_VAL,
	AN7581_PCS_CDR_PR_CAP_EN,
	AN7581_PCS_CDR_PR_INJ_FORCE_OFF,

	AN7581_PCS_CDR_BUF_IN_SR,

	AN7581_PCS_CDR_LPF_TOP_LIM,
	AN7581_PCS_CDR_LPF_RATIO,

	AN7581_PCS_FIELDS_MAX,
};

static const struct reg_field an7581_pcs_fields[AN7581_PCS_FIELDS_MAX] = {
	[AN7581_PCS_CMN_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_CMN_EN, 0, 0),

	[AN7581_PCS_JCPLL_SPARE_L] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SPARE_H, 8, 15),

	[AN7581_PCS_JCPLL_RST_DLY] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_RST_DLY, 0, 2),
	[AN7581_PCS_JCPLL_PLL_RSTB] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_RST_DLY, 8, 8),
	[AN7581_PCS_JCPLL_SDM_DI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_RST_DLY, 16, 16),
	[AN7581_PCS_JCPLL_SDM_DI_LS] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_RST_DLY, 24, 25),

	[AN7581_PCS_JCPLL_SDM_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SDM_IFM, 24, 24),
	[AN7581_PCS_JCPLL_SDM_ORD] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SDM_IFM, 16, 17),
	[AN7581_PCS_JCPLL_SDM_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SDM_IFM, 8, 9),
	[AN7581_PCS_JCPLL_SDM_IFM] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SDM_IFM, 0, 0),
	[AN7581_PCS_JCPLL_SDM_HREN] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SDM_HREN, 0, 0),

	[AN7581_PCS_JCPLL_SSC_PERIOD] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SSC_DELTA, 16, 31),
	[AN7581_PCS_JCPLL_SSC_DELTA] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SSC_DELTA, 0, 15),
	[AN7581_PCS_JCPLL_SSC_DELTA1] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SSC_TRI_EN, 8, 23),
	[AN7581_PCS_JCPLL_SSC_TRI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SSC_TRI_EN, 0, 0),
	[AN7581_PCS_JCPLL_SSC_PHASE_INI] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_VCO_TCLVAR, 17, 17),
	[AN7581_PCS_JCPLL_SSC_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_VCO_TCLVAR, 16, 16),
	[AN7581_PCS_JCPLL_TCL_KBAND_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SPARE_H, 16, 20),

	[AN7581_PCS_JCPLL_CHP_IOFST] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_IB_EXT_EN, 24, 29),
	[AN7581_PCS_JCPLL_CHP_IBIAS] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_IB_EXT_EN, 16, 21),
	[AN7581_PCS_JCPLL_LPF_SHCK_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_IB_EXT_EN, 8, 8),

	[AN7581_PCS_JCPLL_LPF_BWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_LPF_BR, 24, 28),
	[AN7581_PCS_JCPLL_LPF_BP] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_LPF_BR, 16, 20),
	[AN7581_PCS_JCPLL_LPF_BC] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_LPF_BR, 8, 12),
	[AN7581_PCS_JCPLL_LPF_BR] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_LPF_BR, 0, 4),
	[AN7581_PCS_JCPLL_LPF_BWC] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_LPF_BWC, 0, 4),

	[AN7581_PCS_JCPLL_VCO_SCAPWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_VCODIV, 24, 26),
	[AN7581_PCS_JCPLL_VCO_HALFLSB_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_VCODIV, 16, 16),
	[AN7581_PCS_JCPLL_VCO_CFIX] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_VCODIV, 8, 9),
	[AN7581_PCS_JCPLL_VCODIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_VCODIV, 0, 1),
	[AN7581_PCS_JCPLL_VCO_VCOVAR_BIAS_L] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_VCO_TCLVAR, 8, 10),
	[AN7581_PCS_JCPLL_VCO_VCOVAR_BIAS_H] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_VCO_TCLVAR, 3, 5),
	[AN7581_PCS_JCPLL_VCO_TCLVAR] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_VCO_TCLVAR, 0, 2),

	[AN7581_PCS_JCPLL_POSTDIV_D5] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_MMD_PREDIV_MODE, 24, 24),
	[AN7581_PCS_JCPLL_MMD_PREDIV_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_MMD_PREDIV_MODE, 0, 1),

	[AN7581_PCS_JCPLL_KBAND_KS] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_KBAND_KFC, 16, 17),
	[AN7581_PCS_JCPLL_KBAND_KF] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_KBAND_KFC, 8, 9),
	[AN7581_PCS_JCPLL_KBAND_KFC] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_KBAND_KFC, 0, 1),
	[AN7581_PCS_JCPLL_KBAND_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_LPF_BWC, 24, 26),
	[AN7581_PCS_JCPLL_KBAND_CODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_LPF_BWC, 16, 23),
	[AN7581_PCS_JCPLL_KBAND_OPTION] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_LPF_BWC, 8, 8),

	[AN7581_PCS_JCPLL_TCL_AMP_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SDM_HREN, 24, 28),
	[AN7581_PCS_JCPLL_TCL_AMP_GAIN] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SDM_HREN, 16, 18),
	[AN7581_PCS_JCPLL_TCL_AMP_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_SDM_HREN, 8, 8),

	[AN7581_PCS_JCPLL_TCL_LPF_BW] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_TCL_CMP_EN, 24, 26),
	[AN7581_PCS_JCPLL_TCL_LPF_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_JCPLL_TCL_CMP_EN, 16, 16),

	[AN7581_PCS_TXPLL_LDO_VCO_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SSC_PERIOD, 24, 25),
	[AN7581_PCS_TXPLL_LDO_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SSC_PERIOD, 16, 17),
	[AN7581_PCS_TXPLL_PLL_RSTB] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_REFIN_INTERNAL, 24, 24),
	[AN7581_PCS_TXPLL_RST_DLY] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_REFIN_INTERNAL, 16, 18),
	[AN7581_PCS_TXPLL_REFIN_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_REFIN_INTERNAL, 8, 9),
	[AN7581_PCS_TXPLL_REFIN_INTERNAL] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_REFIN_INTERNAL, 0, 0),
	[AN7581_PCS_TXPLL_SDM_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SDM_DI_EN, 24, 25),
	[AN7581_PCS_TXPLL_SDM_IFM] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SDM_DI_EN, 16, 16),
	[AN7581_PCS_TXPLL_SDM_DI_LS] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SDM_DI_EN, 8, 9),
	[AN7581_PCS_TXPLL_SDM_DI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SDM_DI_EN, 0, 0),
	[AN7581_PCS_TXPLL_SDM_HREN] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SDM_ORD, 16, 16),
	[AN7581_PCS_TXPLL_SDM_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SDM_ORD, 8, 8),
	[AN7581_PCS_TXPLL_SDM_ORD] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SDM_ORD, 0, 1),
	[AN7581_PCS_TXPLL_SSC_DELTA1] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SSC_DELTA1, 16, 31),
	[AN7581_PCS_TXPLL_SSC_DELTA] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SSC_DELTA1, 0, 15),
	[AN7581_PCS_TXPLL_SSC_TRI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SSC_EN, 16, 16),
	[AN7581_PCS_TXPLL_SSC_PHASE_INI] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SSC_EN, 8, 8),
	[AN7581_PCS_TXPLL_SSC_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SSC_EN, 0, 0),
	[AN7581_PCS_TXPLL_SSC_PERIOD] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SSC_PERIOD, 0, 15),
	[AN7581_PCS_TXPLL_LPF_BC] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_CHP_IBIAS, 24, 28),
	[AN7581_PCS_TXPLL_LPF_BR] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_CHP_IBIAS, 16, 20),
	[AN7581_PCS_TXPLL_CHP_IOFST] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_CHP_IBIAS, 8, 13),
	[AN7581_PCS_TXPLL_CHP_IBIAS] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_CHP_IBIAS, 0, 5),
	[AN7581_PCS_TXPLL_LPF_BWC] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_LPF_BP, 16, 20),
	[AN7581_PCS_TXPLL_LPF_BWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_LPF_BP, 8, 12),
	[AN7581_PCS_TXPLL_LPF_BP] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_LPF_BP, 0, 4),
	[AN7581_PCS_TXPLL_VCO_CFIX] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_TCL_LPF_EN, 24, 25),
	[AN7581_PCS_TXPLL_VCO_VCOVAR_BIAS_L] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_VCO_HALFLSB_EN, 27, 29),
	[AN7581_PCS_TXPLL_VCO_VCOVAR_BIAS_H] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_VCO_HALFLSB_EN, 24, 26),
	[AN7581_PCS_TXPLL_VCO_TCLVAR] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_VCO_HALFLSB_EN, 16, 18),
	[AN7581_PCS_TXPLL_VCO_SCAPWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_VCO_HALFLSB_EN, 8, 10),
	[AN7581_PCS_TXPLL_VCO_HALFLSB_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_VCO_HALFLSB_EN, 0, 0),
	[AN7581_PCS_TXPLL_KBAND_CODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_KBAND_CODE, 0, 7),
	[AN7581_PCS_TXPLL_KBAND_OPTION] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_LPF_BP, 24, 24),
	[AN7581_PCS_TXPLL_KBAND_KS] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_KBAND_KS, 0, 1),
	[AN7581_PCS_TXPLL_KBAND_KF] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_KBAND_CODE, 24, 25),
	[AN7581_PCS_TXPLL_KBAND_KFC] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_KBAND_CODE, 16, 17),
	[AN7581_PCS_TXPLL_KBAND_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_KBAND_CODE, 8, 10),
	[AN7581_PCS_TXPLL_MMD_PREDIV_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_KBAND_KS, 16, 17),
	[AN7581_PCS_TXPLL_POSTDIV_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_KBAND_KS, 8, 8),
	[AN7581_PCS_TXPLL_VCODIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_TCL_LPF_EN, 16, 17),
	[AN7581_PCS_TXPLL_TCL_KBAND_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_TCL_KBAND_VREF, 0, 4),
	[AN7581_PCS_TXPLL_TCL_AMP_GAIN] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_TCL_AMP_GAIN, 0, 2),
	[AN7581_PCS_TXPLL_TCL_AMP_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_TCL_AMP_GAIN, 8, 12),
	[AN7581_PCS_TXPLL_TCL_LPF_BW] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_TCL_LPF_EN, 8, 10),
	[AN7581_PCS_TXPLL_TCL_LPF_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_TCL_LPF_EN, 0, 0),
	[AN7581_PCS_TXPLL_TCL_AMP_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_TXPLL_SDM_ORD, 24, 24),

	[AN7581_PCS_TX_DMEDGEGEN_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_TX_CKLDO_EN, 24, 24),
	[AN7581_PCS_TX_CKLDO_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_TX_CKLDO_EN, 0, 0),

	[AN7581_PCS_RX_DAC_EYE_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_DAC_D1_BYPASS_AEQ, 24, 24),
	[AN7581_PCS_RX_DAC_E1_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_DAC_D1_BYPASS_AEQ, 16, 16),
	[AN7581_PCS_RX_DAC_E0_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_DAC_D1_BYPASS_AEQ, 8, 8),
	[AN7581_PCS_RX_DAC_D1_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_DAC_D1_BYPASS_AEQ, 0, 0),
	[AN7581_PCS_RX_DAC_D0_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_FE_PEAKING_CTRL_MSB, 24, 24),
	[AN7581_PCS_RX_FE_VCM_GEN_PWDB] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_FE_VCM_GEN_PWDB, 0, 0),

	[AN7581_PCS_AEQ_OFORCE] = REG_FIELD(AIROHA_PCS_ANA_PXP_AEQ_CFORCE, 8, 19),
	[AN7581_PCS_RX_OSCAL_FORCE] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_OSCAL_WATCH_WNDW, 8, 17),

	[AN7581_PCS_CDR_PD_EDGE_DIS] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PD_PICAL_CKD8_INV, 8, 8),
	[AN7581_PCS_CDR_PD_PICAL_CKD8_INV] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PD_PICAL_CKD8_INV, 0, 0),

	[AN7581_PCS_RX_DAC_MON] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_MONPR_EN, 24, 28),
	[AN7581_PCS_CDR_PR_XFICK_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_MONPR_EN, 2, 2),
	[AN7581_PCS_CDR_PR_MONPI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_MONPR_EN, 1, 1),
	[AN7581_PCS_CDR_PR_MONPR_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_MONPR_EN, 0, 0),

	[AN7581_PCS_RX_REV_1_FE_BUF1_BIAS_CTRL] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_REV_0, 24, 26),
	[AN7581_PCS_RX_REV_1_FE_BUF2_BIAS_CTRL] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_REV_0, 20, 22),
	[AN7581_PCS_RX_REV_1_SIGDET_ILEAK] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_REV_0, 18, 19),

	[AN7581_PCS_CDR_LPF_TOP_LIM] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_LPF_RATIO, 8, 26),
	[AN7581_PCS_CDR_LPF_RATIO] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_LPF_RATIO, 0, 1),

	[AN7581_PCS_CDR_PR_KBAND_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_BETA_DAC, 24, 26),
	[AN7581_PCS_CDR_PR_BETA_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_BETA_DAC, 16, 19),
	[AN7581_PCS_CDR_PR_VCOADC_OS] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_BETA_DAC, 8, 11),
	[AN7581_PCS_CDR_PR_BETA_DAC] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_BETA_DAC, 0, 6),
	[AN7581_PCS_CDR_PR_FBKSEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_VREG_IBAND_VAL, 24, 25),
	[AN7581_PCS_CDR_PR_DAC_BAND] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_VREG_IBAND_VAL, 16, 20),
	[AN7581_PCS_CDR_PR_VREG_CKBUF_VAL] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_VREG_IBAND_VAL, 8, 10),
	[AN7581_PCS_CDR_PR_VREG_IBAND_VAL] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_VREG_IBAND_VAL, 0, 2),

	[AN7581_PCS_RX_FE_VB_EQ3_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_FE_EQ_HZEN, 24, 24),
	[AN7581_PCS_RX_FE_VB_EQ2_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_FE_EQ_HZEN, 16, 16),
	[AN7581_PCS_RX_FE_VB_EQ1_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_FE_EQ_HZEN, 8, 8),
	[AN7581_PCS_RX_FE_EQ_HZEN] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_FE_EQ_HZEN, 0, 0),

	[AN7581_PCS_CDR_PR_CAP_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_MONPR_EN, 19, 19),
	[AN7581_PCS_CDR_BUF_IN_SR] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_MONPR_EN, 16, 18),

	[AN7581_PCS_RX_SIGDET_VTH_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_SIGDET_NOVTH, 16, 20),
	[AN7581_PCS_RX_SIGDET_PEAK] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_SIGDET_NOVTH, 8, 9),
	[AN7581_PCS_RX_SIGDET_LPF_CTRL] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_DAC_RANGE, 24, 25),

	[AN7581_PCS_RX_TDC_CK_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_PHYCK_DIV, 24, 24),
	[AN7581_PCS_RX_PHYCK_RSTB] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_PHYCK_DIV, 16, 16),
	[AN7581_PCS_RX_PHYCK_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_PHYCK_DIV, 8, 9),
	[AN7581_PCS_RX_PHYCK_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_PHYCK_DIV, 0, 7),
	[AN7581_PCS_RX_PHY_CK_SEL_FORCE] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_BUSBIT_SEL, 24, 24),
	[AN7581_PCS_RX_PHY_CK_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_RX_BUSBIT_SEL, 16, 16),

	[AN7581_PCS_CDR_PR_INJ_FORCE_OFF] = REG_FIELD(AIROHA_PCS_ANA_PXP_CDR_PR_INJ_MODE, 24, 24),
};

static const struct reg_field an7581_pcs_pcie0_fields[AN7581_PCS_FIELDS_MAX] = {
	[AN7581_PCS_CMN_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CMN_EN, 0, 0),

	[AN7581_PCS_JCPLL_SPARE_L] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_TCL_VTP_EN, 24, 31),

	[AN7581_PCS_JCPLL_RST_DLY] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_RST_DLY, 0, 2),
	[AN7581_PCS_JCPLL_PLL_RSTB] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_RST_DLY, 8, 8),
	[AN7581_PCS_JCPLL_SDM_DI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_RST_DLY, 16, 16),
	[AN7581_PCS_JCPLL_SDM_DI_LS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_RST_DLY, 24, 25),

	[AN7581_PCS_JCPLL_SDM_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_IFM, 24, 24),
	[AN7581_PCS_JCPLL_SDM_ORD] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_IFM, 16, 17),
	[AN7581_PCS_JCPLL_SDM_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_IFM, 8, 9),
	[AN7581_PCS_JCPLL_SDM_IFM] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_IFM, 0, 0),
	[AN7581_PCS_JCPLL_SDM_HREN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_HREN, 0, 0),

	[AN7581_PCS_JCPLL_CHP_IOFST] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_IB_EXT_EN, 24, 29),
	[AN7581_PCS_JCPLL_CHP_IBIAS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_IB_EXT_EN, 16, 21),
	[AN7581_PCS_JCPLL_LPF_SHCK_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_IB_EXT_EN, 8, 8),

	[AN7581_PCS_JCPLL_LPF_BWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BR, 24, 28),
	[AN7581_PCS_JCPLL_LPF_BP] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BR, 16, 20),
	[AN7581_PCS_JCPLL_LPF_BC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BR, 8, 12),
	[AN7581_PCS_JCPLL_LPF_BR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BR, 0, 4),
	[AN7581_PCS_JCPLL_LPF_BWC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BWC, 0, 4),

	[AN7581_PCS_JCPLL_VCO_SCAPWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCODIV, 24, 26),
	[AN7581_PCS_JCPLL_VCO_HALFLSB_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCODIV, 16, 16),
	[AN7581_PCS_JCPLL_VCO_CFIX] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCODIV, 8, 9),
	[AN7581_PCS_JCPLL_VCODIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCODIV, 0, 1),
	[AN7581_PCS_JCPLL_VCO_VCOVAR_BIAS_L] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCO_TCLVAR, 16, 18),
	[AN7581_PCS_JCPLL_VCO_VCOVAR_BIAS_H] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCO_TCLVAR, 8, 10),
	[AN7581_PCS_JCPLL_VCO_TCLVAR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCO_TCLVAR, 0, 2),

	[AN7581_PCS_JCPLL_SSC_DELTA] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_DELTA1, 16, 31),
	[AN7581_PCS_JCPLL_SSC_DELTA1] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_DELTA1, 0, 15),
	[AN7581_PCS_JCPLL_SSC_PERIOD] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_PERIOD, 0, 15),
	[AN7581_PCS_JCPLL_SSC_TRI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_EN, 16, 16),
	[AN7581_PCS_JCPLL_SSC_PHASE_INI] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_EN, 8, 8),
	[AN7581_PCS_JCPLL_SSC_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_EN, 0, 0),
	[AN7581_PCS_JCPLL_TCL_KBAND_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_TCL_KBAND_VREF, 0, 4),

	[AN7581_PCS_JCPLL_POSTDIV_D5] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_MMD_PREDIV_MODE, 24, 24),
	[AN7581_PCS_JCPLL_MMD_PREDIV_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_MMD_PREDIV_MODE, 0, 1),

	[AN7581_PCS_JCPLL_KBAND_KS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_KBAND_KFC, 16, 17),
	[AN7581_PCS_JCPLL_KBAND_KF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_KBAND_KFC, 8, 9),
	[AN7581_PCS_JCPLL_KBAND_KFC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_KBAND_KFC, 0, 1),
	[AN7581_PCS_JCPLL_KBAND_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BWC, 24, 26),
	[AN7581_PCS_JCPLL_KBAND_CODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BWC, 16, 23),
	[AN7581_PCS_JCPLL_KBAND_OPTION] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BWC, 8, 8),

	[AN7581_PCS_JCPLL_TCL_AMP_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_HREN, 24, 28),
	[AN7581_PCS_JCPLL_TCL_AMP_GAIN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_HREN, 16, 18),
	[AN7581_PCS_JCPLL_TCL_AMP_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_HREN, 8, 8),

	[AN7581_PCS_JCPLL_TCL_LPF_BW] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_TCL_CMP_EN, 24, 26),
	[AN7581_PCS_JCPLL_TCL_LPF_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_TCL_CMP_EN, 16, 16),

	[AN7581_PCS_TXPLL_LDO_VCO_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_PERIOD, 24, 25),
	[AN7581_PCS_TXPLL_LDO_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_PERIOD, 16, 17),
	[AN7581_PCS_TXPLL_PLL_RSTB] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_REFIN_DIV, 16, 16),
	[AN7581_PCS_TXPLL_RST_DLY] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_REFIN_DIV, 8, 10),
	[AN7581_PCS_TXPLL_REFIN_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_REFIN_DIV, 0, 1),
	[AN7581_PCS_TXPLL_REFIN_INTERNAL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_PHY_CK2_EN, 24, 24),
	[AN7581_PCS_TXPLL_SDM_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_DI_LS, 16, 17),
	[AN7581_PCS_TXPLL_SDM_IFM] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_DI_LS, 8, 8),
	[AN7581_PCS_TXPLL_SDM_DI_LS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_DI_LS, 0, 1),
	[AN7581_PCS_TXPLL_SDM_DI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_REFIN_DIV, 24, 24),
	[AN7581_PCS_TXPLL_SDM_HREN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_OUT, 8, 8),
	[AN7581_PCS_TXPLL_SDM_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_OUT, 0, 0),
	[AN7581_PCS_TXPLL_SDM_ORD] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_DI_LS, 24, 25),
	[AN7581_PCS_TXPLL_SSC_DELTA1] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_DELTA1, 16, 31),
	[AN7581_PCS_TXPLL_SSC_DELTA] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_DELTA1, 0, 15),
	[AN7581_PCS_TXPLL_SSC_TRI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_EN, 16, 16),
	[AN7581_PCS_TXPLL_SSC_PHASE_INI] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_EN, 8, 8),
	[AN7581_PCS_TXPLL_SSC_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_EN, 0, 0),
	[AN7581_PCS_TXPLL_SSC_PERIOD] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_PERIOD, 0, 15),
	[AN7581_PCS_TXPLL_LPF_BC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_CHP_IOFST, 16, 20),
	[AN7581_PCS_TXPLL_LPF_BR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_CHP_IOFST, 8, 12),
	[AN7581_PCS_TXPLL_CHP_IOFST] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_CHP_IOFST, 0, 5),
	[AN7581_PCS_TXPLL_CHP_IBIAS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_750M_SYS_CK_EN, 24, 29),
	[AN7581_PCS_TXPLL_LPF_BWC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_LPF_BWR, 8, 12),
	[AN7581_PCS_TXPLL_LPF_BWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_LPF_BWR, 0, 4),
	[AN7581_PCS_TXPLL_LPF_BP] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_CHP_IOFST, 24, 28),
	[AN7581_PCS_TXPLL_VCO_CFIX] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_LPF_BW, 16, 17),
	[AN7581_PCS_TXPLL_VCO_VCOVAR_BIAS_L] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_VCO_SCAPWR, 24, 26),
	[AN7581_PCS_TXPLL_VCO_VCOVAR_BIAS_H] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_VCO_SCAPWR, 16, 18),
	[AN7581_PCS_TXPLL_VCO_TCLVAR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_VCO_SCAPWR, 8, 10),
	[AN7581_PCS_TXPLL_VCO_SCAPWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_VCO_SCAPWR, 0, 2),
	[AN7581_PCS_TXPLL_VCO_HALFLSB_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_LPF_BW, 24, 24),
	[AN7581_PCS_TXPLL_KBAND_CODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_LPF_BWR, 24, 31),
	[AN7581_PCS_TXPLL_KBAND_OPTION] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_LPF_BWR, 16, 16),
	[AN7581_PCS_TXPLL_KBAND_KS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_KBAND_DIV, 24, 25),
	[AN7581_PCS_TXPLL_KBAND_KF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_KBAND_DIV, 16, 17),
	[AN7581_PCS_TXPLL_KBAND_KFC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_KBAND_DIV, 8, 9),
	[AN7581_PCS_TXPLL_KBAND_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_KBAND_DIV, 0, 2),
	[AN7581_PCS_TXPLL_MMD_PREDIV_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_POSTDIV_EN, 8, 9),
	[AN7581_PCS_TXPLL_POSTDIV_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_POSTDIV_EN, 0, 0),
	[AN7581_PCS_TXPLL_VCODIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_LPF_BW, 8, 9),
	[AN7581_PCS_TXPLL_TCL_KBAND_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_KBAND_VREF, 0, 4),
	[AN7581_PCS_TXPLL_TCL_AMP_GAIN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_OUT, 24, 26),
	[AN7581_PCS_TXPLL_TCL_AMP_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_AMP_VREF, 0, 4),
	[AN7581_PCS_TXPLL_TCL_LPF_BW] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_LPF_BW, 0, 2),
	[AN7581_PCS_TXPLL_TCL_LPF_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_AMP_VREF, 24, 24),
	[AN7581_PCS_TXPLL_TCL_AMP_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_OUT, 16, 16),

	[AN7581_PCS_TX_DMEDGEGEN_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TX0_CKLDO_EN, 24, 24),
	[AN7581_PCS_TX_CKLDO_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TX0_CKLDO_EN, 0, 0),

	[AN7581_PCS_RX_DAC_EYE_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_DAC_EYE_BYPASS_AEQ, 0, 0),
	[AN7581_PCS_RX_DAC_E1_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_DAC_D0_BYPASS_AEQ, 24, 24),
	[AN7581_PCS_RX_DAC_E0_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_DAC_D0_BYPASS_AEQ, 16, 16),
	[AN7581_PCS_RX_DAC_D1_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_DAC_D0_BYPASS_AEQ, 8, 8),
	[AN7581_PCS_RX_DAC_D0_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_DAC_D0_BYPASS_AEQ, 0, 0),
	[AN7581_PCS_RX_FE_VCM_GEN_PWDB] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_FE_VB_EQ2_EN, 16, 16),

	[AN7581_PCS_AEQ_OFORCE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_AEQ0_CFORCE, 8, 19),
	[AN7581_PCS_RX_OSCAL_FORCE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_OSCAL_FORCE, 8, 17),

	[AN7581_PCS_CDR_PD_EDGE_DIS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PD_PICAL_CKD8_INV, 8, 8),
	[AN7581_PCS_CDR_PD_PICAL_CKD8_INV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PD_PICAL_CKD8_INV, 0, 0),

	[AN7581_PCS_RX_DAC_MON] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_DAC_MON, 0, 4),
	[AN7581_PCS_CDR_PR_XFICK_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_MONPI_EN, 8, 8),
	[AN7581_PCS_CDR_PR_MONPI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_MONPI_EN, 0, 0),
	[AN7581_PCS_CDR_PR_MONPR_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_COR_HBW_EN, 24, 24),

	[AN7581_PCS_RX_REV_1_FE_BUF1_BIAS_CTRL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_REV_0, 24, 26),
	[AN7581_PCS_RX_REV_1_FE_BUF2_BIAS_CTRL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_REV_0, 20, 22),
	[AN7581_PCS_RX_REV_1_SIGDET_ILEAK] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_REV_0, 18, 19),

	[AN7581_PCS_CDR_LPF_TOP_LIM] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_LPF_RATIO, 8, 26),
	[AN7581_PCS_CDR_LPF_RATIO] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_LPF_RATIO, 0, 1),

	[AN7581_PCS_CDR_PR_KBAND_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_BETA_DAC, 24, 26),
	[AN7581_PCS_CDR_PR_BETA_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_BETA_DAC, 16, 19),
	[AN7581_PCS_CDR_PR_VCOADC_OS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_BETA_DAC, 8, 11),
	[AN7581_PCS_CDR_PR_BETA_DAC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_BETA_DAC, 0, 6),
	[AN7581_PCS_CDR_PR_FBKSEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_VREG_IBAND_VAL, 24, 25),
	[AN7581_PCS_CDR_PR_DAC_BAND] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_VREG_IBAND_VAL, 16, 20),
	[AN7581_PCS_CDR_PR_VREG_CKBUF_VAL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_VREG_IBAND_VAL, 8, 10),
	[AN7581_PCS_CDR_PR_VREG_IBAND_VAL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_VREG_IBAND_VAL, 0, 2),

	[AN7581_PCS_RX_FE_VB_EQ3_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_FE_VB_EQ2_EN, 8, 8),
	[AN7581_PCS_RX_FE_VB_EQ2_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_FE_VB_EQ2_EN, 0, 0),
	[AN7581_PCS_RX_FE_VB_EQ1_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_SIGDET_VTH_SEL, 24, 24),
	[AN7581_PCS_RX_FE_EQ_HZEN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_SIGDET_VTH_SEL, 16, 16),

	[AN7581_PCS_CDR_PR_CAP_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_BUF_IN_SR, 8, 8),
	[AN7581_PCS_CDR_BUF_IN_SR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_BUF_IN_SR, 0, 2),

	[AN7581_PCS_RX_SIGDET_VTH_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_SIGDET_VTH_SEL, 0, 4),
	[AN7581_PCS_RX_SIGDET_PEAK] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_SIGDET_DCTEST_EN, 24, 25),
	[AN7581_PCS_RX_SIGDET_LPF_CTRL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_SIGDET_DCTEST_EN, 8, 9),

	[AN7581_PCS_RX_TDC_CK_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_PHYCK_DIV, 24, 24),
	[AN7581_PCS_RX_PHYCK_RSTB] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_PHYCK_DIV, 16, 16),
	[AN7581_PCS_RX_PHYCK_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_PHYCK_DIV, 8, 9),
	[AN7581_PCS_RX_PHYCK_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_PHYCK_DIV, 0, 7),
	[AN7581_PCS_RX_PHY_CK_SEL_FORCE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_BUSBIT_SEL, 24, 24),
	[AN7581_PCS_RX_PHY_CK_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX0_BUSBIT_SEL, 16, 16),

	[AN7581_PCS_CDR_PR_INJ_FORCE_OFF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR0_PR_INJ_MODE, 24, 24),
};

static const struct reg_field an7581_pcs_pcie1_fields[AN7581_PCS_FIELDS_MAX] = {
	[AN7581_PCS_CMN_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CMN_EN, 0, 0),

	[AN7581_PCS_JCPLL_SPARE_L] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_TCL_VTP_EN, 24, 31),

	[AN7581_PCS_JCPLL_RST_DLY] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_RST_DLY, 0, 2),
	[AN7581_PCS_JCPLL_PLL_RSTB] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_RST_DLY, 8, 8),
	[AN7581_PCS_JCPLL_SDM_DI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_RST_DLY, 16, 16),
	[AN7581_PCS_JCPLL_SDM_DI_LS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_RST_DLY, 24, 25),

	[AN7581_PCS_JCPLL_SDM_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_IFM, 24, 24),
	[AN7581_PCS_JCPLL_SDM_ORD] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_IFM, 16, 17),
	[AN7581_PCS_JCPLL_SDM_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_IFM, 8, 9),
	[AN7581_PCS_JCPLL_SDM_IFM] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_IFM, 0, 0),
	[AN7581_PCS_JCPLL_SDM_HREN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_HREN, 0, 0),

	[AN7581_PCS_JCPLL_CHP_IOFST] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_IB_EXT_EN, 24, 29),
	[AN7581_PCS_JCPLL_CHP_IBIAS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_IB_EXT_EN, 16, 21),
	[AN7581_PCS_JCPLL_LPF_SHCK_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_IB_EXT_EN, 8, 8),

	[AN7581_PCS_JCPLL_LPF_BWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BR, 24, 28),
	[AN7581_PCS_JCPLL_LPF_BP] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BR, 16, 20),
	[AN7581_PCS_JCPLL_LPF_BC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BR, 8, 12),
	[AN7581_PCS_JCPLL_LPF_BR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BR, 0, 4),
	[AN7581_PCS_JCPLL_LPF_BWC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BWC, 0, 4),

	[AN7581_PCS_JCPLL_VCO_SCAPWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCODIV, 24, 26),
	[AN7581_PCS_JCPLL_VCO_HALFLSB_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCODIV, 16, 16),
	[AN7581_PCS_JCPLL_VCO_CFIX] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCODIV, 8, 9),
	[AN7581_PCS_JCPLL_VCODIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCODIV, 0, 1),
	[AN7581_PCS_JCPLL_VCO_VCOVAR_BIAS_L] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCO_TCLVAR, 16, 18),
	[AN7581_PCS_JCPLL_VCO_VCOVAR_BIAS_H] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCO_TCLVAR, 8, 10),
	[AN7581_PCS_JCPLL_VCO_TCLVAR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_VCO_TCLVAR, 0, 2),

	[AN7581_PCS_JCPLL_SSC_DELTA] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_DELTA1, 16, 31),
	[AN7581_PCS_JCPLL_SSC_DELTA1] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_DELTA1, 0, 15),
	[AN7581_PCS_JCPLL_SSC_PERIOD] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_PERIOD, 0, 15),
	[AN7581_PCS_JCPLL_SSC_TRI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_EN, 16, 16),
	[AN7581_PCS_JCPLL_SSC_PHASE_INI] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_EN, 8, 8),
	[AN7581_PCS_JCPLL_SSC_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SSC_EN, 0, 0),
	[AN7581_PCS_JCPLL_TCL_KBAND_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_TCL_KBAND_VREF, 0, 4),

	[AN7581_PCS_JCPLL_POSTDIV_D5] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_MMD_PREDIV_MODE, 24, 24),
	[AN7581_PCS_JCPLL_MMD_PREDIV_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_MMD_PREDIV_MODE, 0, 1),

	[AN7581_PCS_JCPLL_KBAND_KS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_KBAND_KFC, 16, 17),
	[AN7581_PCS_JCPLL_KBAND_KF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_KBAND_KFC, 8, 9),
	[AN7581_PCS_JCPLL_KBAND_KFC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_KBAND_KFC, 0, 1),
	[AN7581_PCS_JCPLL_KBAND_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BWC, 24, 26),
	[AN7581_PCS_JCPLL_KBAND_CODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BWC, 16, 23),
	[AN7581_PCS_JCPLL_KBAND_OPTION] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_LPF_BWC, 8, 8),

	[AN7581_PCS_JCPLL_TCL_AMP_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_HREN, 24, 28),
	[AN7581_PCS_JCPLL_TCL_AMP_GAIN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_HREN, 16, 18),
	[AN7581_PCS_JCPLL_TCL_AMP_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_SDM_HREN, 8, 8),

	[AN7581_PCS_JCPLL_TCL_LPF_BW] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_TCL_CMP_EN, 24, 26),
	[AN7581_PCS_JCPLL_TCL_LPF_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_JCPLL_TCL_CMP_EN, 16, 16),

	[AN7581_PCS_TXPLL_LDO_VCO_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_PERIOD, 24, 25),
	[AN7581_PCS_TXPLL_LDO_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_PERIOD, 16, 17),
	[AN7581_PCS_TXPLL_PLL_RSTB] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_REFIN_DIV, 16, 16),
	[AN7581_PCS_TXPLL_RST_DLY] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_REFIN_DIV, 8, 10),
	[AN7581_PCS_TXPLL_REFIN_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_REFIN_DIV, 0, 1),
	[AN7581_PCS_TXPLL_REFIN_INTERNAL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_PHY_CK2_EN, 24, 24),
	[AN7581_PCS_TXPLL_SDM_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_DI_LS, 16, 17),
	[AN7581_PCS_TXPLL_SDM_IFM] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_DI_LS, 8, 8),
	[AN7581_PCS_TXPLL_SDM_DI_LS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_DI_LS, 0, 1),
	[AN7581_PCS_TXPLL_SDM_DI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_REFIN_DIV, 24, 24),
	[AN7581_PCS_TXPLL_SDM_HREN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_OUT, 8, 8),
	[AN7581_PCS_TXPLL_SDM_OUT] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_OUT, 0, 0),
	[AN7581_PCS_TXPLL_SDM_ORD] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_DI_LS, 24, 25),
	[AN7581_PCS_TXPLL_SSC_DELTA1] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_DELTA1, 16, 31),
	[AN7581_PCS_TXPLL_SSC_DELTA] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_DELTA1, 0, 15),
	[AN7581_PCS_TXPLL_SSC_TRI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_EN, 16, 16),
	[AN7581_PCS_TXPLL_SSC_PHASE_INI] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_EN, 8, 8),
	[AN7581_PCS_TXPLL_SSC_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_EN, 0, 0),
	[AN7581_PCS_TXPLL_SSC_PERIOD] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SSC_PERIOD, 0, 15),
	[AN7581_PCS_TXPLL_LPF_BC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_CHP_IOFST, 16, 20),
	[AN7581_PCS_TXPLL_LPF_BR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_CHP_IOFST, 8, 12),
	[AN7581_PCS_TXPLL_CHP_IOFST] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_CHP_IOFST, 0, 5),
	[AN7581_PCS_TXPLL_CHP_IBIAS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_750M_SYS_CK_EN, 24, 29),
	[AN7581_PCS_TXPLL_LPF_BWC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_LPF_BWR, 8, 12),
	[AN7581_PCS_TXPLL_LPF_BWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_LPF_BWR, 0, 4),
	[AN7581_PCS_TXPLL_LPF_BP] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_CHP_IOFST, 24, 28),
	[AN7581_PCS_TXPLL_VCO_CFIX] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_LPF_BW, 16, 17),
	[AN7581_PCS_TXPLL_VCO_VCOVAR_BIAS_L] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_VCO_SCAPWR, 24, 26),
	[AN7581_PCS_TXPLL_VCO_VCOVAR_BIAS_H] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_VCO_SCAPWR, 16, 18),
	[AN7581_PCS_TXPLL_VCO_TCLVAR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_VCO_SCAPWR, 8, 10),
	[AN7581_PCS_TXPLL_VCO_SCAPWR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_VCO_SCAPWR, 0, 2),
	[AN7581_PCS_TXPLL_VCO_HALFLSB_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_LPF_BW, 24, 24),
	[AN7581_PCS_TXPLL_KBAND_CODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_LPF_BWR, 24, 31),
	[AN7581_PCS_TXPLL_KBAND_OPTION] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_LPF_BWR, 16, 16),
	[AN7581_PCS_TXPLL_KBAND_KS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_KBAND_DIV, 24, 25),
	[AN7581_PCS_TXPLL_KBAND_KF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_KBAND_DIV, 16, 17),
	[AN7581_PCS_TXPLL_KBAND_KFC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_KBAND_DIV, 8, 9),
	[AN7581_PCS_TXPLL_KBAND_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_KBAND_DIV, 0, 2),
	[AN7581_PCS_TXPLL_MMD_PREDIV_MODE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_POSTDIV_EN, 8, 9),
	[AN7581_PCS_TXPLL_POSTDIV_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_POSTDIV_EN, 0, 0),
	[AN7581_PCS_TXPLL_VCODIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_LPF_BW, 8, 9),
	[AN7581_PCS_TXPLL_TCL_KBAND_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_KBAND_VREF, 0, 4),
	[AN7581_PCS_TXPLL_TCL_AMP_GAIN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_OUT, 24, 26),
	[AN7581_PCS_TXPLL_TCL_AMP_VREF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_AMP_VREF, 0, 4),
	[AN7581_PCS_TXPLL_TCL_LPF_BW] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_LPF_BW, 0, 2),
	[AN7581_PCS_TXPLL_TCL_LPF_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_TCL_AMP_VREF, 24, 24),
	[AN7581_PCS_TXPLL_TCL_AMP_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TXPLL_SDM_OUT, 16, 16),

	[AN7581_PCS_TX_DMEDGEGEN_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TX1_CKLDO_EN, 24, 24),
	[AN7581_PCS_TX_CKLDO_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_TX1_CKLDO_EN, 0, 0),

	[AN7581_PCS_RX_DAC_EYE_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_DAC_D1_BYPASS_AEQ, 24, 24),
	[AN7581_PCS_RX_DAC_E1_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_DAC_D1_BYPASS_AEQ, 16, 16),
	[AN7581_PCS_RX_DAC_E0_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_DAC_D1_BYPASS_AEQ, 8, 8),
	[AN7581_PCS_RX_DAC_D1_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_DAC_D1_BYPASS_AEQ, 0, 0),
	[AN7581_PCS_RX_DAC_D0_BYPASS_AEQ] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_FE_PEACKING_CTRL_LSB, 24, 24),
	[AN7581_PCS_RX_FE_VCM_GEN_PWDB] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_FE_VB_EQ1_EN, 24, 24),

	[AN7581_PCS_AEQ_OFORCE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_AEQ1_CFORCE, 16, 27),
	[AN7581_PCS_RX_OSCAL_FORCE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_OSCAL_WATCH_WNDW, 16, 25),

	[AN7581_PCS_CDR_PD_EDGE_DIS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PD_PICAL_CKD8_INV, 8, 8),
	[AN7581_PCS_CDR_PD_PICAL_CKD8_INV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PD_PICAL_CKD8_INV, 0, 0),

	[AN7581_PCS_RX_DAC_MON] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_BUF_IN_SR, 16, 20),
	[AN7581_PCS_CDR_PR_XFICK_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_MONPI_EN, 8, 8),
	[AN7581_PCS_CDR_PR_MONPI_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_MONPI_EN, 0, 0),
	[AN7581_PCS_CDR_PR_MONPR_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_COR_HBW_EN, 24, 24),

	[AN7581_PCS_RX_REV_1_FE_BUF1_BIAS_CTRL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_REV_0, 24, 26),
	[AN7581_PCS_RX_REV_1_FE_BUF2_BIAS_CTRL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_REV_0, 20, 22),
	[AN7581_PCS_RX_REV_1_SIGDET_ILEAK] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_REV_0, 18, 19),

	[AN7581_PCS_CDR_LPF_TOP_LIM] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_LPF_RATIO, 8, 26),
	[AN7581_PCS_CDR_LPF_RATIO] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_LPF_RATIO, 0, 1),

	[AN7581_PCS_CDR_PR_KBAND_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_BETA_DAC, 24, 26),
	[AN7581_PCS_CDR_PR_BETA_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_BETA_DAC, 16, 19),
	[AN7581_PCS_CDR_PR_VCOADC_OS] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_BETA_DAC, 8, 11),
	[AN7581_PCS_CDR_PR_BETA_DAC] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_BETA_DAC, 0, 6),
	[AN7581_PCS_CDR_PR_FBKSEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_VREG_IBAND_VAL, 24, 25),
	[AN7581_PCS_CDR_PR_DAC_BAND] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_VREG_IBAND_VAL, 16, 20),
	[AN7581_PCS_CDR_PR_VREG_CKBUF_VAL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_VREG_IBAND_VAL, 8, 10),
	[AN7581_PCS_CDR_PR_VREG_IBAND_VAL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_VREG_IBAND_VAL, 0, 2),

	[AN7581_PCS_RX_FE_VB_EQ3_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_FE_VB_EQ1_EN, 16, 16),
	[AN7581_PCS_RX_FE_VB_EQ2_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_FE_VB_EQ1_EN, 8, 8),
	[AN7581_PCS_RX_FE_VB_EQ1_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_FE_VB_EQ1_EN, 0, 0),
	[AN7581_PCS_RX_FE_EQ_HZEN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_FE_50OHMS_SEL, 24, 24),

	[AN7581_PCS_CDR_PR_CAP_EN] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_BUF_IN_SR, 8, 8),
	[AN7581_PCS_CDR_BUF_IN_SR] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_BUF_IN_SR, 0, 2),

	[AN7581_PCS_RX_SIGDET_VTH_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_SIGDET_NOVTH, 16, 20),
	[AN7581_PCS_RX_SIGDET_PEAK] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_SIGDET_NOVTH, 8, 9),
	[AN7581_PCS_RX_SIGDET_LPF_CTRL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_DAC_RANGE_EYE, 24, 25),

	[AN7581_PCS_RX_TDC_CK_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_PHYCK_DIV, 24, 24),
	[AN7581_PCS_RX_PHYCK_RSTB] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_PHYCK_DIV, 16, 16),
	[AN7581_PCS_RX_PHYCK_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_PHYCK_DIV, 8, 9),
	[AN7581_PCS_RX_PHYCK_DIV] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_PHYCK_DIV, 0, 7),
	[AN7581_PCS_RX_PHY_CK_SEL_FORCE] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_BUSBIT_SEL, 24, 24),
	[AN7581_PCS_RX_PHY_CK_SEL] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_RX1_BUSBIT_SEL, 16, 16),

	[AN7581_PCS_CDR_PR_INJ_FORCE_OFF] = REG_FIELD(AIROHA_PCS_ANA_PXP_2L_CDR1_PR_INJ_MODE, 24, 24),
};

static void an7581_pcs_jcpll_bringup(struct airoha_pcs_priv *priv,
				     int index, phy_interface_t interface)
{
	struct regmap_field **pcs_ana_fields = priv->pcs_ana_fields[index];
	struct regmap *pcs_pma;
	u32 kband_vref;

	switch (interface) {
	case PHY_INTERFACE_MODE_SGMII:
	case PHY_INTERFACE_MODE_1000BASEX:
	case PHY_INTERFACE_MODE_2500BASEX:
		kband_vref = 0x10;
		break;
	case PHY_INTERFACE_MODE_USXGMII:
	case PHY_INTERFACE_MODE_10GBASER:
		kband_vref = 0xf;
		break;
	default:
		return;
	}

	/* This comment only apply to Serdes PCIe that expose
	 * 2 PCS.
	 *
	 * The Serdes PCIe expose 2 PCS but always require
	 * the PMA for the first PCS to be configured
	 * for correct functionality for JCPLL.
	 */
	pcs_pma = priv->pcs_pma[0];

	/* Setup LDO */
	usleep_range(200, 300);

	regmap_field_set_bits(pcs_ana_fields[AN7581_PCS_JCPLL_SPARE_L],
			      AIROHA_PCS_ANA_JCPLL_SPARE_L_LDO);

	/* Setup RSTB */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_RST_DLY],
			   AIROHA_PCS_ANA_JCPLL_RST_DLY_150_200);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_PLL_RSTB], 0x1);

	/* Enable PLL force selection and Force Disable */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_JCPLL_CKOUT_EN,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_JCPLL_EN |
			   AIROHA_PCS_PMA_FORCE_DA_JCPLL_EN,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_JCPLL_EN);

	/* Setup SDM */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SDM_DI_LS],
			   AIROHA_PCS_ANA_JCPLL_SDM_DI_LS_2_23);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SDM_DI_EN], 0x0);

	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SDM_OUT], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SDM_ORD],
			   AIROHA_PCS_ANA_JCPLL_SDM_ORD_3SDM);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SDM_MODE], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SDM_IFM], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SDM_HREN], 0x0);

	/* Setup SSC */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SSC_DELTA], 0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SSC_DELTA1], 0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SSC_PERIOD], 0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SSC_TRI_EN], 0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SSC_EN], 0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_SSC_PHASE_INI], 0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_VCO_TCLVAR], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_VCO_VCOVAR_BIAS_L], 0);

	/* Setup LPF */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_CHP_IOFST], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_CHP_IBIAS], 0x18);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_LPF_SHCK_EN], 0);

	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_LPF_BWR], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_LPF_BP], 0x10);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_LPF_BC], 0x1f);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_LPF_BR], BIT(3) | BIT(1));
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_LPF_BWC], 0x0);

	/* Setup VCO */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_VCO_SCAPWR], 0x4);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_VCO_HALFLSB_EN], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_VCO_CFIX], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_VCO_VCOVAR_BIAS_L], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_VCO_VCOVAR_BIAS_H], 0x3);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_VCO_TCLVAR], 0x3);

	/* Setup PCW */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_JCPLL_SDM_PCW,
			   AIROHA_PCS_PMA_FORCE_DA_JCPLL_SDM_PCW,
			   FIELD_PREP(AIROHA_PCS_PMA_FORCE_DA_JCPLL_SDM_PCW, 0x25800000));

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_RX_FE_VOS,
			AIROHA_PCS_PMA_FORCE_SEL_DA_JCPLL_SDM_PCW);

	/* Setup DIV */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_POSTDIV_D5], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_MMD_PREDIV_MODE],
			   AIROHA_PCS_ANA_JCPLL_MMD_PREDIV_MODE_2);

	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_VCODIV],
			   AIROHA_PCS_ANA_JCPLL_VCODIV_1);

	/* Setup KBand */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_KBAND_KS], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_KBAND_KF], 0x3);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_KBAND_KFC], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_KBAND_DIV], 0x2);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_KBAND_CODE], 0xe4);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_KBAND_OPTION], 0x0);

	/* Setup TCL */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_TCL_KBAND_VREF],
			   kband_vref);

	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_TCL_AMP_VREF], 0x5);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_TCL_AMP_GAIN],
			   AIROHA_PCS_ANA_JCPLL_TCL_AMP_GAIN_4);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_TCL_AMP_EN], 0x1);

	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_TCL_LPF_BW],
			   AIROHA_PCS_ANA_JCPLL_TCL_LPF_BW_1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_JCPLL_TCL_LPF_EN], 0x1);

	/* Enable PLL */
	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_JCPLL_CKOUT_EN,
			AIROHA_PCS_PMA_FORCE_DA_JCPLL_EN);

	/* Enale PLL Output */
	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_JCPLL_CKOUT_EN,
			AIROHA_PCS_PMA_FORCE_SEL_DA_JCPLL_CKOUT_EN |
			AIROHA_PCS_PMA_FORCE_DA_JCPLL_CKOUT_EN);
}

static void an7581_pcs_txpll_bringup(struct airoha_pcs_priv *priv,
				     int index, phy_interface_t interface)
{
	struct regmap_field **pcs_ana_fields = priv->pcs_ana_fields[index];
	u32 lpf_chp_ibias, lpf_bp, lpf_bwr, lpf_bwc;
	struct regmap *pcs_pma;
	u32 tcl_amp_vref;
	bool sdm_hren;
	u32 vco_cfix;
	bool vcodiv;
	u32 pcw;

	switch (interface) {
	case PHY_INTERFACE_MODE_SGMII:
	case PHY_INTERFACE_MODE_1000BASEX:
		lpf_chp_ibias = 0xf;
		lpf_bp = BIT(1);
		lpf_bwr = BIT(3) | BIT(1) | BIT(0);
		lpf_bwc = BIT(4) | BIT(3);
		vco_cfix = BIT(1) | BIT(0);
		pcw = BIT(27);
		tcl_amp_vref = BIT(3) | BIT(1) | BIT(0);
		vcodiv = false;
		sdm_hren = false;
		break;
	case PHY_INTERFACE_MODE_2500BASEX:
		lpf_chp_ibias = 0xa;
		lpf_bp = BIT(2) | BIT(0);
		lpf_bwr = 0;
		lpf_bwc = 0;
		vco_cfix = 0;
		pcw = BIT(27) | BIT(25);
		tcl_amp_vref = BIT(3) | BIT(2) | BIT(0);
		vcodiv = true;
		sdm_hren = false;
		break;
	case PHY_INTERFACE_MODE_USXGMII:
	case PHY_INTERFACE_MODE_10GBASER:
		lpf_chp_ibias = 0xf;
		lpf_bp = BIT(1);
		lpf_bwr = BIT(3) | BIT(1) | BIT(0);
		lpf_bwc = BIT(4) | BIT(3);
		vco_cfix = BIT(0);
		pcw = BIT(27) | BIT(22);
		tcl_amp_vref = BIT(3) | BIT(1) | BIT(0);
		vcodiv = false;
		sdm_hren = true;
		break;
	default:
		return;
	}

	/* This comment only apply to Serdes PCIe that expose
	 * 2 PCS.
	 *
	 * The Serdes PCIe expose 2 PCS but always require
	 * the PMA for the first PCS to be configured
	 * for correct functionality for TXPLL.
	 */
	pcs_pma = priv->pcs_pma[0];

	/* Setup VCO LDO Output */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_LDO_VCO_OUT], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_LDO_OUT], 0x1);

	/* Setup RSTB */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_PLL_RSTB], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_RST_DLY], 0x4);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_REFIN_DIV],
			   AIROHA_PCS_ANA_TXPLL_REFIN_DIV_1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_REFIN_INTERNAL], 0x1);

	/* Enable PLL force selection and Force Disable */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_TXPLL_CKOUT_EN,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TXPLL_EN |
			   AIROHA_PCS_PMA_FORCE_DA_TXPLL_EN,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TXPLL_EN);

	/* Setup SDM */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SDM_MODE], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SDM_IFM], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SDM_DI_LS],
			   AIROHA_PCS_ANA_TXPLL_SDM_DI_LS_2_23);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SDM_DI_EN], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SDM_HREN], sdm_hren);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SDM_OUT], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SDM_ORD],
			   AIROHA_PCS_ANA_TXPLL_SDM_ORD_3SDM);

	/* Setup SSC */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SSC_DELTA1], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SSC_DELTA], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SSC_TRI_EN], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SSC_PHASE_INI], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SSC_EN], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_SSC_PERIOD], 0x0);

	/* Setup LPF */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_CHP_IBIAS],
			   lpf_chp_ibias);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_CHP_IOFST], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_LPF_BC], 0x1f);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_LPF_BR], 0x5);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_LPF_BWC], lpf_bwc);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_LPF_BWR], lpf_bwr);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_LPF_BP], lpf_bp);

	/* Setup VCO */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_VCO_CFIX], vco_cfix);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_VCO_VCOVAR_BIAS_L], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_VCO_VCOVAR_BIAS_H], 0x4);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_VCO_TCLVAR], 0x4);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_VCO_SCAPWR], 0x7);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_VCO_HALFLSB_EN], 0x1);

	/* Setup PCW */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_TXPLL_SDM_PCW,
			   AIROHA_PCS_PMA_FORCE_DA_TXPLL_SDM_PCW, pcw);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_IDAC,
			AIROHA_PCS_PMA_FORCE_SEL_DA_TXPLL_SDM_PCW);

	/* Setup KBand */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_KBAND_CODE], 0xe4);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_KBAND_OPTION], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_KBAND_KS], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_KBAND_KF], 0x3);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_KBAND_KFC], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_KBAND_DIV], 0x4);

	/* Setup DIV */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_POSTDIV_EN], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_MMD_PREDIV_MODE],
			   AIROHA_PCS_ANA_TXPLL_MMD_PREDIV_MODE_2);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_VCODIV],
			   vcodiv ? AIROHA_PCS_ANA_TXPLL_VCODIV_2 :
				    AIROHA_PCS_ANA_TXPLL_VCODIV_1);

	/* Setup TCL */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_TCL_KBAND_VREF], 0xf);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_TCL_AMP_VREF],
			   tcl_amp_vref);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_TCL_AMP_GAIN],
			   AIROHA_PCS_ANA_TXPLL_TCL_AMP_GAIN_4);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_TCL_LPF_BW],
			   AIROHA_PCS_ANA_TXPLL_TCL_LPF_BW_0_5);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_TCL_LPF_EN], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TXPLL_TCL_AMP_EN], 0x1);

	/* Enable PLL */
	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_TXPLL_CKOUT_EN,
			AIROHA_PCS_PMA_FORCE_DA_TXPLL_EN);

	/* Enale PLL Output */
	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_TXPLL_CKOUT_EN,
			AIROHA_PCS_PMA_FORCE_SEL_DA_TXPLL_CKOUT_EN |
			AIROHA_PCS_PMA_FORCE_DA_TXPLL_CKOUT_EN);
}

static void an7581_pcs_tx_bringup(struct airoha_pcs_priv *priv,
				  int index, phy_interface_t interface)
{
	struct regmap_field **pcs_ana_fields = priv->pcs_ana_fields[index];
	struct regmap *pcs_pma = priv->pcs_pma[index];
	u32 fir_cn1, fir_c0b, fir_c1;
	u32 tx_rate_ctrl;
	u32 ckin_divisor;
	u32 xfi_tx_mode;

	switch (interface) {
	case PHY_INTERFACE_MODE_SGMII:
	case PHY_INTERFACE_MODE_1000BASEX:
		ckin_divisor = BIT(1);
		tx_rate_ctrl = BIT(0);
		fir_cn1 = 0;
		fir_c0b = 12;
		fir_c1 = 0;
		xfi_tx_mode = AIROHA_PCS_PMA_XFI_TX_MODE_1G25;
		break;
	case PHY_INTERFACE_MODE_2500BASEX:
		ckin_divisor = BIT(2);
		tx_rate_ctrl = BIT(0);
		fir_cn1 = 0;
		fir_c0b = 11;
		fir_c1 = 1;
		xfi_tx_mode = AIROHA_PCS_PMA_XFI_TX_MODE_3G12;
		break;
	case PHY_INTERFACE_MODE_USXGMII:
	case PHY_INTERFACE_MODE_10GBASER:
		ckin_divisor = BIT(2) | BIT(0);
		tx_rate_ctrl = BIT(1);
		fir_cn1 = 1;
		fir_c0b = 1;
		fir_c1 = 11;
		xfi_tx_mode = AIROHA_PCS_PMA_XFI_TX_MODE_10G3;
		break;
	default:
		return;
	}

	/* Set TX rate ctrl */
	if (priv->data->port_type == AIROHA_PCS_PCIE) {
		regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_DIG_RESERVE_29,
				   AIROHA_PCS_PMA_2L_TX_RATE_CTRL,
				   FIELD_PREP(AIROHA_PCS_PMA_2L_TX_RATE_CTRL,
					      tx_rate_ctrl));

		regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_ADD_XPON_MODE_1,
				   AIROHA_PCS_PMA_XFI_TX_MODE,
				   xfi_tx_mode);
	} else {
		regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_XPON_TX_RATE_CTRL,
				   AIROHA_PCS_PMA_PON_TX_RATE_CTRL,
				   FIELD_PREP(AIROHA_PCS_PMA_PON_TX_RATE_CTRL,
					      tx_rate_ctrl));
	}

	/* Setup TX Config */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TX_DMEDGEGEN_EN], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_TX_CKLDO_EN], 0x1);

	udelay(1);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_TX_ACJTAG_EN,
			AIROHA_PCS_PMA_FORCE_SEL_DA_TX_CKIN_SEL |
			AIROHA_PCS_PMA_FORCE_DA_TX_CKIN_SEL);

	/* FIXME: Ask Airoha TX term is OK to reset? */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_TX_TERM_SEL,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_CKIN_DIVISOR |
			   AIROHA_PCS_PMA_FORCE_DA_TX_CKIN_DIVISOR |
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_TERM_SEL |
			   AIROHA_PCS_PMA_FORCE_DA_TX_TERM_SEL,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_CKIN_DIVISOR |
			   FIELD_PREP(AIROHA_PCS_PMA_FORCE_DA_TX_CKIN_DIVISOR,
				      ckin_divisor));

	if (priv->data->port_type != AIROHA_PCS_PCIE) {
		regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_TX_RATE_CTRL,
				   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_RATE_CTRL |
				   AIROHA_PCS_PMA_FORCE_DA_TX_RATE_CTRL,
				   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_RATE_CTRL |
				   FIELD_PREP(AIROHA_PCS_PMA_FORCE_DA_TX_RATE_CTRL,
					      tx_rate_ctrl));
	}

	/* Setup TX FIR Load Parameters (Reference 660mV) */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_TX_FIR_C0B,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_FIR_CN1 |
			   AIROHA_PCS_PMA_FORCE_DA_TX_FIR_CN1 |
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_FIR_C0B |
			   AIROHA_PCS_PMA_FORCE_DA_TX_FIR_C0B,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_FIR_CN1 |
			   FIELD_PREP(AIROHA_PCS_PMA_FORCE_DA_TX_FIR_CN1, fir_cn1) |
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_FIR_C0B |
			   FIELD_PREP(AIROHA_PCS_PMA_FORCE_DA_TX_FIR_C0B, fir_c0b));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_TX_FIR_C1,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_FIR_C2 |
			   AIROHA_PCS_PMA_FORCE_DA_TX_FIR_C2 |
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_FIR_C1 |
			   AIROHA_PCS_PMA_FORCE_DA_TX_FIR_C1,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_TX_FIR_C1 |
			   FIELD_PREP(AIROHA_PCS_PMA_FORCE_DA_TX_FIR_C1, fir_c1));

	/* Reset TX Bar */
	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_TX_RST_B,
			AIROHA_PCS_PMA_TXCALIB_RST_B | AIROHA_PCS_PMA_TX_TOP_RST_B);
}

static void an7581_pcs_rx_bringup(struct airoha_pcs_priv *priv,
				  int index, phy_interface_t interface)
{
	struct regmap_field **pcs_ana_fields = priv->pcs_ana_fields[index];
	struct regmap *pcs_pma = priv->pcs_pma[index];
	u32 phyck_div, phyck_sel;
	u32 pr_cdr_beta_dac;
	u32 cdr_pr_buf_in_sr;
	bool cdr_pr_cap_en;
	u32 sigdet_vth_sel;
	u32 rx_rate_ctrl;
	u32 xfi_rx_mode;
	u32 osr;

	switch (interface) {
	case PHY_INTERFACE_MODE_SGMII:
	case PHY_INTERFACE_MODE_1000BASEX:
		osr = BIT(1) | BIT(0); /* 1.25G */
		pr_cdr_beta_dac = BIT(3);
		rx_rate_ctrl = 0;
		cdr_pr_cap_en = false;
		cdr_pr_buf_in_sr = BIT(2) | BIT(1) | BIT(0);
		sigdet_vth_sel = BIT(2) | BIT(1);
		phyck_div = BIT(5) | BIT(3) | BIT(0);
		phyck_sel = BIT(0);
		xfi_rx_mode = AIROHA_PCS_PMA_XFI_RX_MODE_1G25;
		break;
	case PHY_INTERFACE_MODE_2500BASEX:
		osr = BIT(0); /* 2.5G */
		pr_cdr_beta_dac = BIT(2) | BIT(1);
		rx_rate_ctrl = 0;
		cdr_pr_cap_en = true;
		cdr_pr_buf_in_sr = BIT(2) | BIT(1);
		sigdet_vth_sel = BIT(2) | BIT(1);
		phyck_div = BIT(3) | BIT(1) | BIT(0);
		phyck_sel = BIT(0);
		xfi_rx_mode = AIROHA_PCS_PMA_XFI_RX_MODE_3G12;
		break;
	case PHY_INTERFACE_MODE_USXGMII:
	case PHY_INTERFACE_MODE_10GBASER:
		osr = 0; /* 10G */
		cdr_pr_cap_en = false;
		pr_cdr_beta_dac = BIT(3);
		rx_rate_ctrl = BIT(1);
		cdr_pr_buf_in_sr = BIT(2) | BIT(1) | BIT(0);
		sigdet_vth_sel = BIT(1);
		phyck_div = BIT(6) | BIT(1);
		phyck_sel = BIT(1);
		xfi_rx_mode = AIROHA_PCS_PMA_XFI_RX_MODE_10G3;
		break;
	default:
		return;
	}

	/* Set RX rate ctrl */
	if (interface == PHY_INTERFACE_MODE_2500BASEX)
		regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_FLL_2,
				   AIROHA_PCS_PMA_CK_RATE,
				   AIROHA_PCS_PMA_CK_RATE_10);

	if (priv->data->port_type == AIROHA_PCS_PCIE) {
		regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_DIG_RESERVE_29,
				   AIROHA_PCS_PMA_2L_RX_RATE_CTRL,
				   FIELD_PREP(AIROHA_PCS_PMA_2L_RX_RATE_CTRL,
					      rx_rate_ctrl));

		regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_ADD_XPON_MODE_1,
				   AIROHA_PCS_PMA_XFI_RX_MODE,
				   xfi_rx_mode);
	} else {
		regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_XPON_RX_RESERVED_1,
				   AIROHA_PCS_PMA_XPON_RX_RATE_CTRL,
				   FIELD_PREP(AIROHA_PCS_PMA_XPON_RX_RATE_CTRL,
					      rx_rate_ctrl));
	}

	/* Setup RX Path */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_FLL_5,
			   AIROHA_PCS_PMA_FLL_IDAC_MIN |
			   AIROHA_PCS_PMA_FLL_IDAC_MAX,
			   FIELD_PREP(AIROHA_PCS_PMA_FLL_IDAC_MIN, 0x400) |
			   FIELD_PREP(AIROHA_PCS_PMA_FLL_IDAC_MAX, 0x3ff));

	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_DAC_EYE_BYPASS_AEQ], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_DAC_E1_BYPASS_AEQ], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_DAC_E0_BYPASS_AEQ], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_DAC_D1_BYPASS_AEQ], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_DAC_D0_BYPASS_AEQ], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_FE_VCM_GEN_PWDB], 0x1);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_SS_LCPLL_PWCTL_SETTING_1,
			AIROHA_PCS_PMA_LCPLL_MAN_PWDB);

	regmap_field_write(pcs_ana_fields[AN7581_PCS_AEQ_OFORCE],
			   AIROHA_PCS_ANA_AEQ_OFORCE_CTLE);

	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_OSCAL_FORCE],
			   AIROHA_PCS_ANA_RX_OSCAL_FORCE_VGA2VOS |
			   AIROHA_PCS_ANA_RX_OSCAL_FORCE_VGA2IOS |
			   AIROHA_PCS_ANA_RX_OSCAL_FORCE_VGA1VOS |
			   AIROHA_PCS_ANA_RX_OSCAL_FORCE_VGA1IOS |
			   AIROHA_PCS_ANA_RX_OSCAL_FORCE_CTLE2VOS |
			   AIROHA_PCS_ANA_RX_OSCAL_FORCE_CTLE2IOS |
			   AIROHA_PCS_ANA_RX_OSCAL_FORCE_CTLE1VOS |
			   AIROHA_PCS_ANA_RX_OSCAL_FORCE_CTLE1IOS |
			   AIROHA_PCS_ANA_RX_OSCAL_FORCE_LVSH |
			   AIROHA_PCS_ANA_RX_OSCAL_FORCE_COMPOS);

	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_RX_DISB_MODE_4,
			  AIROHA_PCS_PMA_DISB_BLWC_OFFSET);

	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_RX_EXTRAL_CTRL,
			  AIROHA_PCS_PMA_DISB_LEQ);

	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PD_EDGE_DIS], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PD_PICAL_CKD8_INV], 0x0);

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_AEQ_BYPASS,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_AEQ_CKON |
			   AIROHA_PCS_PMA_FORCE_DA_AEQ_CKON,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_AEQ_CKON);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_AEQ_RSTB,
			AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_INJCK_SEL |
			AIROHA_PCS_PMA_FORCE_DA_CDR_INJCK_SEL);

	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_DAC_MON], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_XFICK_EN], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_MONPI_EN], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_MONPR_EN], 0x0);

	/* Setup FE Gain and FE Peacking */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_FE_GAIN_CTRL,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_RX_FE_GAIN_CTRL |
			   AIROHA_PCS_PMA_FORCE_DA_RX_FE_GAIN_CTRL,
			   FIELD_PREP(AIROHA_PCS_PMA_FORCE_DA_RX_FE_GAIN_CTRL, 0x0));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_JCPLL_SDM_SCAN,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_RX_FE_PEAKING_CTRL |
			   AIROHA_PCS_PMA_FORCE_DA_RX_FE_PEAKING_CTRL,
			   FIELD_PREP(AIROHA_PCS_PMA_FORCE_DA_RX_FE_PEAKING_CTRL, 0x0));

	/* Setup FE VOS */
	if (interface != PHY_INTERFACE_MODE_USXGMII &&
	    interface != PHY_INTERFACE_MODE_10GBASER)
		regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_RX_FE_VOS,
				   AIROHA_PCS_PMA_FORCE_SEL_DA_FE_VOS |
				   AIROHA_PCS_PMA_FORCE_DA_FE_VOS,
				   AIROHA_PCS_PMA_FORCE_SEL_DA_FE_VOS |
				   FIELD_PREP(AIROHA_PCS_PMA_FORCE_DA_FE_VOS, 0x0));

	/* Setup FLL PR FMeter (no bypass mode)*/
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PLL_TDC_FREQDET_0,
			   AIROHA_PCS_PMA_PLL_LOCK_CYCLECNT,
			   FIELD_PREP(AIROHA_PCS_PMA_PLL_LOCK_CYCLECNT, 0x1));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PLL_TDC_FREQDET_1,
			   AIROHA_PCS_PMA_PLL_LOCK_TARGET_END |
			   AIROHA_PCS_PMA_PLL_LOCK_TARGET_BEG,
			   FIELD_PREP(AIROHA_PCS_PMA_PLL_LOCK_TARGET_END, 0xffff) |
			   FIELD_PREP(AIROHA_PCS_PMA_PLL_LOCK_TARGET_BEG, 0x0));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PLL_TDC_FREQDET_3,
			   AIROHA_PCS_PMA_PLL_LOCK_LOCKTH,
			   FIELD_PREP(AIROHA_PCS_PMA_PLL_LOCK_LOCKTH, 0x1));

	/* FIXME: Warn and Ask Airoha about typo in air_eth_xsgmii.c line 1391 */
	/* AIROHA_PCS_ANA_REV_1_FE_BUF1_BIAS_CTRL is set 0x0 in SDK but seems a typo */
	/* Setup REV */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_REV_1_FE_BUF1_BIAS_CTRL],
			   BIT(2));
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_REV_1_FE_BUF2_BIAS_CTRL],
			   BIT(2));
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_REV_1_SIGDET_ILEAK], 0x0);

	/* Setup Rdy Timeout */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_CTRL_SEQUENCE_CTRL_5,
			   AIROHA_PCS_PMA_RX_RDY |
			   AIROHA_PCS_PMA_RX_BLWC_RDY_EN,
			   FIELD_PREP(AIROHA_PCS_PMA_RX_RDY, 0xa) |
			   FIELD_PREP(AIROHA_PCS_PMA_RX_BLWC_RDY_EN, 0x5));

	/* Setup CaBoundry Init */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_CTRL_SEQUENCE_CTRL_0,
			   AIROHA_PCS_PMA_RX_OS_START |
			   AIROHA_PCS_PMA_OSC_SPEED_OPT,
			   FIELD_PREP(AIROHA_PCS_PMA_RX_OS_START, 0x1) |
			   AIROHA_PCS_PMA_OSC_SPEED_OPT_0_1);

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_CTRL_SEQUENCE_CTRL_6,
			   AIROHA_PCS_PMA_RX_OS_END,
			   FIELD_PREP(AIROHA_PCS_PMA_RX_OS_END, 0x2));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_CTRL_SEQUENCE_CTRL_1,
			   AIROHA_PCS_PMA_RX_PICAL_END |
			   AIROHA_PCS_PMA_RX_PICAL_START,
			   FIELD_PREP(AIROHA_PCS_PMA_RX_PICAL_END, 0x32) |
			   FIELD_PREP(AIROHA_PCS_PMA_RX_PICAL_START, 0x2));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_CTRL_SEQUENCE_CTRL_4,
			   AIROHA_PCS_PMA_RX_SDCAL_END |
			   AIROHA_PCS_PMA_RX_SDCAL_START,
			   FIELD_PREP(AIROHA_PCS_PMA_RX_SDCAL_END, 0x32) |
			   FIELD_PREP(AIROHA_PCS_PMA_RX_SDCAL_START, 0x2));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_CTRL_SEQUENCE_CTRL_2,
			   AIROHA_PCS_PMA_RX_PDOS_END |
			   AIROHA_PCS_PMA_RX_PDOS_START,
			   FIELD_PREP(AIROHA_PCS_PMA_RX_PDOS_END, 0x32) |
			   FIELD_PREP(AIROHA_PCS_PMA_RX_PDOS_START, 0x2));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_CTRL_SEQUENCE_CTRL_3,
			   AIROHA_PCS_PMA_RX_FEOS_END |
			   AIROHA_PCS_PMA_RX_FEOS_START,
			   FIELD_PREP(AIROHA_PCS_PMA_RX_FEOS_END, 0x32) |
			   FIELD_PREP(AIROHA_PCS_PMA_RX_FEOS_START, 0x2));

	/* Setup By Serdes*/
	/* Setup RX OSR */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_AEQ_SPEED,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_OSR_SEL |
			   AIROHA_PCS_PMA_FORCE_DA_OSR_SEL,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_OSR_SEL |
			   FIELD_PREP(AIROHA_PCS_PMA_FORCE_DA_OSR_SEL, osr));

	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PD_EDGE_DIS], !!osr);

	/* Setup CDR LPF Ratio */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_LPF_TOP_LIM], 0x20000);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_LPF_RATIO], osr);

	/* Setup CDR PR */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_KBAND_DIV], 0x4);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_BETA_SEL], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_VCOADC_OS], 0x8);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_BETA_DAC],
			   pr_cdr_beta_dac);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_FBKSEL], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_DAC_BAND],
			   pr_cdr_beta_dac);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_VREG_CKBUF_VAL], 0x6);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_VREG_IBAND_VAL], 0x6);

	/* Setup Eye Mon */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PHY_EQ_CTRL_2,
			   AIROHA_PCS_PMA_EQ_DEBUG_SEL |
			   AIROHA_PCS_PMA_FOM_NUM_ORDER |
			   AIROHA_PCS_PMA_A_SEL,
			   FIELD_PREP(AIROHA_PCS_PMA_EQ_DEBUG_SEL, 0x0) |
			   FIELD_PREP(AIROHA_PCS_PMA_FOM_NUM_ORDER, 0x1) |
			   FIELD_PREP(AIROHA_PCS_PMA_A_SEL, 0x3));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_EYE_TOP_EYECNT_CTRL_2,
			   AIROHA_PCS_PMA_DATA_SHIFT |
			   AIROHA_PCS_PMA_EYECNT_FAST,
			   AIROHA_PCS_PMA_EYECNT_FAST);

	/* Calibration Start */

	/* Enable SYS */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_SYS_EN_SEL_0,
			   AIROHA_PCS_PMA_RX_SYS_EN_SEL,
			   FIELD_PREP(AIROHA_PCS_PMA_RX_SYS_EN_SEL, 0x1));

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_SS_LCPLL_PWCTL_SETTING_0,
			AIROHA_PCS_PMA_SW_LCPLL_EN);

	usleep_range(500, 600);

	/* Setup FLL PR FMeter (bypass mode)*/
	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_RX_DISB_MODE_8,
			  AIROHA_PCS_PMA_DISB_FBCK_LOCK);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_RX_FORCE_MODE_9,
			AIROHA_PCS_PMA_FORCE_FBCK_LOCK);

	/* Enable CMLEQ */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_FE_EQ_HZEN], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_FE_VB_EQ3_EN], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_FE_VB_EQ2_EN], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_FE_VB_EQ1_EN], 0x1);

	/* Setup CDR PR */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_CAP_EN],
			   cdr_pr_cap_en);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_BUF_IN_SR],
			   cdr_pr_buf_in_sr);

	/* Setup CDR xxx Pwdb, set force and disable */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_PIEYE_PWDB,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_PWDB |
			   AIROHA_PCS_PMA_FORCE_DA_CDR_PR_PWDB |
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_PIEYE_PWDB |
			   AIROHA_PCS_PMA_FORCE_DA_CDR_PR_PIEYE_PWDB,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_PWDB |
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_PIEYE_PWDB);

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PD_PWDB,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_KBAND_RSTB |
			   AIROHA_PCS_PMA_FORCE_DA_CDR_PR_KBAND_RSTB |
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PD_PWDB |
			   AIROHA_PCS_PMA_FORCE_DA_CDR_PR_PD_PWDB,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PD_PWDB);

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_RX_FE_PWDB,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_RX_PDOSCAL_EN |
			   AIROHA_PCS_PMA_FORCE_DA_RX_PDOSCAL_EN |
			   AIROHA_PCS_PMA_FORCE_SEL_DA_RX_FE_PWDB |
			   AIROHA_PCS_PMA_FORCE_DA_RX_FE_PWDB,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_RX_FE_PWDB);

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_RX_SCAN_RST_B,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_RX_SIGDET_PWDB |
			   AIROHA_PCS_PMA_FORCE_DA_RX_SIGDET_PWDB |
			   AIROHA_PCS_PMA_FORCE_SEL_DA_RX_SCAN_RST_B |
			   AIROHA_PCS_PMA_FORCE_DA_RX_SCAN_RST_B,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_RX_SIGDET_PWDB);

	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_SS_DA_XPON_PWDB_0,
			  AIROHA_PCS_PMA_XPON_CDR_PD_PWDB |
			  AIROHA_PCS_PMA_XPON_CDR_PR_PIEYE_PWDB |
			  AIROHA_PCS_PMA_XPON_CDR_PW_PWDB |
			  AIROHA_PCS_PMA_XPON_RX_FE_PWDB);

	/* FIXME: Ask Airoha WHY it's cleared? */
	/* regmap_clear_bits(priv->pcs_ana, AIROHA_PCS_ANA_PXP_RX_SIGDET_NOVTH,
	 *		  AIROHA_PCS_ANA_RX_FE_50OHMS_SEL);
	 */

	/* Setup SigDet */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_SIGDET_VTH_SEL],
			   sigdet_vth_sel);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_SIGDET_PEAK],
			   BIT(1));
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_SIGDET_LPF_CTRL],
			   BIT(1) | BIT(0));

	/* Disable SigDet Pwdb */
	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_SS_DA_XPON_PWDB_1,
			  AIROHA_PCS_PMA_RX_SIDGET_PWDB);

	/* Setup PHYCK */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_TDC_CK_SEL], 0x0);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_PHYCK_RSTB], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_PHYCK_SEL],
			   phyck_sel);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_PHYCK_DIV],
			   phyck_div);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_PHY_CK_SEL_FORCE], 0x1);
	regmap_field_write(pcs_ana_fields[AN7581_PCS_RX_PHY_CK_SEL], 0x0);

	usleep_range(100, 200);

	/* Enable CDR xxx Pwdb */
	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_PIEYE_PWDB,
			AIROHA_PCS_PMA_FORCE_DA_CDR_PR_PWDB |
			AIROHA_PCS_PMA_FORCE_DA_CDR_PR_PIEYE_PWDB);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PD_PWDB,
			AIROHA_PCS_PMA_FORCE_DA_CDR_PR_PD_PWDB);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_RX_FE_PWDB,
			AIROHA_PCS_PMA_FORCE_DA_RX_FE_PWDB);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_RX_SCAN_RST_B,
			AIROHA_PCS_PMA_FORCE_DA_RX_SIGDET_PWDB);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_SS_DA_XPON_PWDB_0,
			AIROHA_PCS_PMA_XPON_CDR_PD_PWDB |
			AIROHA_PCS_PMA_XPON_CDR_PR_PIEYE_PWDB |
			AIROHA_PCS_PMA_XPON_CDR_PW_PWDB |
			AIROHA_PCS_PMA_XPON_RX_FE_PWDB);

	/* Enable SigDet Pwdb */
	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_SS_DA_XPON_PWDB_1,
			AIROHA_PCS_PMA_RX_SIDGET_PWDB);
}

static unsigned int an7581_pcs_apply_cdr_pr_idac(struct airoha_pcs_priv *priv,
						 int index, u32 cdr_pr_idac)
{
	struct regmap *pcs_pma = priv->pcs_pma[index];
	u32 val = UINT_MAX;

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_IDAC,
			   AIROHA_PCS_PMA_FORCE_CDR_PR_IDAC,
			   FIELD_PREP(AIROHA_PCS_PMA_FORCE_CDR_PR_IDAC,
				      cdr_pr_idac));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_SS_RX_FREQ_DET_4,
			   AIROHA_PCS_PMA_FREQLOCK_DET_EN,
			   AIROHA_PCS_PMA_FREQLOCK_DET_EN_FORCE_0);

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_SS_RX_FREQ_DET_4,
			   AIROHA_PCS_PMA_FREQLOCK_DET_EN,
			   AIROHA_PCS_PMA_FREQLOCK_DET_EN_NORMAL);

	usleep_range(5000, 7000);

	regmap_read(pcs_pma, AIROHA_PCS_PMA_RX_FREQDET, &val);

	return FIELD_GET(AIROHA_PCS_PMA_FL_OUT, val);
}

static u32 an7581_pcs_rx_prcal_idac_major(struct airoha_pcs_priv *priv,
					  int index, u32 target_fl_out)
{
	unsigned int fl_out_diff = UINT_MAX;
	unsigned int prcal_search;
	u32 cdr_pr_idac = 0;

	for (prcal_search = 0; prcal_search < 8 ; prcal_search++) {
		unsigned int fl_out_diff_new;
		unsigned int fl_out;
		u32 cdr_pr_idac_tmp;

		/* try to find the upper value by setting the last 3 bit */
		cdr_pr_idac_tmp = FIELD_PREP(AIROHA_PCS_PMA_FORCE_CDR_PR_IDAC_MAJOR,
					     prcal_search);
		fl_out = an7581_pcs_apply_cdr_pr_idac(priv, index, cdr_pr_idac_tmp);

		/* Use absolute values to find the closest one to target */
		fl_out_diff_new = abs_diff(fl_out, target_fl_out);
		dev_dbg(priv->dev, "Tested CDR Pr Idac: %x Fl Out: %x Diff: %u\n",
			cdr_pr_idac_tmp, fl_out, fl_out_diff_new);
		if (fl_out_diff_new < fl_out_diff) {
			cdr_pr_idac = cdr_pr_idac_tmp;
			fl_out_diff = fl_out_diff_new;
		}
	}

	return cdr_pr_idac;
}

static u32 an7581_pcs_rx_prcal_idac_minor(struct airoha_pcs_priv *priv, int index,
					  u32 target_fl_out, u32 cdr_pr_idac_major)
{
	unsigned int remaining_prcal_search_bits = 0;
	u32 cdr_pr_idac = cdr_pr_idac_major;
	unsigned int fl_out, fl_out_diff;
	int best_prcal_search_bit = -1;
	int prcal_search_bit;

	fl_out = an7581_pcs_apply_cdr_pr_idac(priv, index, cdr_pr_idac);
	fl_out_diff = abs_diff(fl_out, target_fl_out);

	/* Deadline search part.
	 * We start from top bits to bottom as we progressively decrease the
	 * signal.
	 */
	for (prcal_search_bit = 7; prcal_search_bit >= 0; prcal_search_bit--) {
		unsigned int fl_out_diff_new;
		u32 cdr_pr_idac_tmp;

		cdr_pr_idac_tmp = cdr_pr_idac | BIT(prcal_search_bit);
		fl_out = an7581_pcs_apply_cdr_pr_idac(priv, index, cdr_pr_idac_tmp);

		/* Use absolute values to find the closest one to target */
		fl_out_diff_new = abs_diff(fl_out, target_fl_out);
		dev_dbg(priv->dev, "Tested CDR Pr Idac: %x Fl Out: %x Diff: %u\n",
			cdr_pr_idac_tmp, fl_out, fl_out_diff_new);
		if (fl_out_diff_new < fl_out_diff) {
			best_prcal_search_bit = prcal_search_bit;
			fl_out_diff = fl_out_diff_new;
		}
	}

	/* Set the idac with the best value we found and
	 * reset the search bit to start from bottom to top.
	 */
	if (best_prcal_search_bit >= 0) {
		cdr_pr_idac |= BIT(best_prcal_search_bit);
		remaining_prcal_search_bits = best_prcal_search_bit;
		prcal_search_bit = 0;
	}

	/* Fine tune part.
	 * Test remaining bits to find an even closer signal level to target
	 * by increasing the signal.
	 */
	while (remaining_prcal_search_bits) {
		unsigned int fl_out_diff_new;
		u32 cdr_pr_idac_tmp;

		cdr_pr_idac_tmp = cdr_pr_idac | BIT(prcal_search_bit);
		fl_out = an7581_pcs_apply_cdr_pr_idac(priv, index, cdr_pr_idac_tmp);

		/* Use absolute values to find the closest one to target */
		fl_out_diff_new = abs_diff(fl_out, target_fl_out);
		/* Assume we found the deadline when the new absolue signal difference
		 * from target is greater than the previous and the difference is at
		 * least 10% greater between the old and new value.
		 * This is to account for signal detection level tollerance making
		 * sure we are actually over a deadline (AKA we are getting farther
		 * from target)
		 */
		dev_dbg(priv->dev, "Tested CDR Pr Idac: %x Fl Out: %x Diff: %u\n",
			cdr_pr_idac_tmp, fl_out, fl_out_diff_new);

		/* Exact match, set the bit and exit */
		if (!fl_out_diff_new) {
			cdr_pr_idac |= BIT(prcal_search_bit);
			break;
		}

		if (fl_out_diff && fl_out_diff_new > fl_out_diff &&
		    (abs_diff(fl_out_diff_new, fl_out_diff) * 100) / fl_out_diff > 10) {
			/* Exit early if we are already at the deadline */
			if (prcal_search_bit == 0)
				break;

			/* We found the deadline, set the value to the previous
			 * bit, and reset the loop to fine tune with the
			 * remaining values.
			 */
			cdr_pr_idac |= BIT(prcal_search_bit - 1);
			remaining_prcal_search_bits = prcal_search_bit - 1;
			prcal_search_bit = 0;
		} else {
			/* Update the signal level diff and try the next bit */
			fl_out_diff = fl_out_diff_new;

			/* If we didn't found the deadline, set the last bit
			 * and reset the loop to fine tune with the remainig
			 * values.
			 */
			if (prcal_search_bit == remaining_prcal_search_bits - 1) {
				cdr_pr_idac |= BIT(prcal_search_bit);
				remaining_prcal_search_bits = prcal_search_bit;
				prcal_search_bit = 0;
			} else {
				prcal_search_bit++;
			}
		}
	}

	return cdr_pr_idac;
}

static void an7581_pcs_rx_prcal(struct airoha_pcs_priv *priv,
				int index, phy_interface_t interface)
{
	struct regmap_field **pcs_ana_fields = priv->pcs_ana_fields[index];
	struct regmap *pcs_pma = priv->pcs_pma[index];
	u32 cdr_pr_idac_major, cdr_pr_idac;
	unsigned int fl_out, fl_out_diff;

	u32 target_fl_out;
	u32 cyclecnt;

	switch (interface) {
	case PHY_INTERFACE_MODE_SGMII:  /* DS_1.25G      / US_1.25G  */
	case PHY_INTERFACE_MODE_1000BASEX:
		target_fl_out = 0xa3d6;
		cyclecnt = 32767;
		break;
	case PHY_INTERFACE_MODE_2500BASEX: /* DS_9.95328G   / US_9.95328G */
		target_fl_out = 0xa000;
		cyclecnt = 20000;
		break;
	case PHY_INTERFACE_MODE_USXGMII: /* DS_10.3125G  / US_1.25G */
	case PHY_INTERFACE_MODE_10GBASER:
		target_fl_out = 0x9edf;
		cyclecnt = 32767;
		break;
	default:
		return;
	}

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_SW_RST_SET,
			AIROHA_PCS_PMA_SW_REF_RST_N);

	usleep_range(100, 200);

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_SS_RX_FREQ_DET_2,
			   AIROHA_PCS_PMA_LOCK_TARGET_END |
			   AIROHA_PCS_PMA_LOCK_TARGET_BEG,
			   FIELD_PREP(AIROHA_PCS_PMA_LOCK_TARGET_END, target_fl_out + 100) |
			   FIELD_PREP(AIROHA_PCS_PMA_LOCK_TARGET_BEG, target_fl_out - 100));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_SS_RX_FREQ_DET_1,
			   AIROHA_PCS_PMA_UNLOCK_CYCLECNT |
			   AIROHA_PCS_PMA_LOCK_CYCLECNT,
			   FIELD_PREP(AIROHA_PCS_PMA_UNLOCK_CYCLECNT, cyclecnt) |
			   FIELD_PREP(AIROHA_PCS_PMA_LOCK_CYCLECNT, cyclecnt));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_SS_RX_FREQ_DET_4,
			   AIROHA_PCS_PMA_LOCK_UNLOCKTH |
			   AIROHA_PCS_PMA_LOCK_LOCKTH,
			   FIELD_PREP(AIROHA_PCS_PMA_LOCK_UNLOCKTH, 3) |
			   FIELD_PREP(AIROHA_PCS_PMA_LOCK_LOCKTH, 3));

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_SS_RX_FREQ_DET_3,
			   AIROHA_PCS_PMA_UNLOCK_TARGET_END |
			   AIROHA_PCS_PMA_UNLOCK_TARGET_BEG,
			   FIELD_PREP(AIROHA_PCS_PMA_UNLOCK_TARGET_END, target_fl_out + 100) |
			   FIELD_PREP(AIROHA_PCS_PMA_UNLOCK_TARGET_BEG, target_fl_out - 100));

	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_INJ_FORCE_OFF], 0x1);

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_LPF_C_EN,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_LPF_R_EN |
			   AIROHA_PCS_PMA_FORCE_DA_CDR_PR_LPF_R_EN |
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_LPF_C_EN |
			   AIROHA_PCS_PMA_FORCE_DA_CDR_PR_LPF_C_EN,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_LPF_R_EN |
			   AIROHA_PCS_PMA_FORCE_DA_CDR_PR_LPF_R_EN |
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_LPF_C_EN);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_IDAC,
			AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_IDAC);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_PIEYE_PWDB,
			AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_PWDB);

	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_PIEYE_PWDB,
			  AIROHA_PCS_PMA_FORCE_DA_CDR_PR_PWDB);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_PIEYE_PWDB,
			AIROHA_PCS_PMA_FORCE_DA_CDR_PR_PWDB);

	/* Calibration logic:
	 * First check the major value by looping with every
	 * value in the last 3 bit of CDR_PR_IDAC.
	 * Get the signal level and save the value that is closer to
	 * the target.
	 *
	 * Then check each remaining 7 bits in search of the deadline
	 * where the signal gets farther than signal target.
	 *
	 * Finally fine tune for the remaining bits to find the one that
	 * produce the closest signal level.
	 */
	cdr_pr_idac_major = an7581_pcs_rx_prcal_idac_major(priv, index, target_fl_out);

	cdr_pr_idac = an7581_pcs_rx_prcal_idac_minor(priv, index,
						     target_fl_out, cdr_pr_idac_major);

	fl_out = an7581_pcs_apply_cdr_pr_idac(priv, index, cdr_pr_idac);
	fl_out_diff = abs_diff(fl_out, target_fl_out);
	if (fl_out_diff > 100) {
		u32 pr_idac_major = FIELD_GET(AIROHA_PCS_PMA_FORCE_CDR_PR_IDAC_MAJOR,
					      cdr_pr_idac_major);
		unsigned int fl_out_tmp, fl_out_diff_tmp;
		u32 cdr_pr_idac_tmp;

		if (pr_idac_major > 0) {
			cdr_pr_idac_tmp = FIELD_PREP(AIROHA_PCS_PMA_FORCE_CDR_PR_IDAC_MAJOR,
						     pr_idac_major - 1);

			dev_dbg(priv->dev, "Fl Out is %d far from target %d with Pr Idac %x. Trying with Pr Idac %x.\n",
				fl_out_diff, target_fl_out, cdr_pr_idac_major, cdr_pr_idac_tmp);

			cdr_pr_idac_tmp = an7581_pcs_rx_prcal_idac_minor(priv, index,
									 target_fl_out,
									 cdr_pr_idac_tmp);

			fl_out_tmp = an7581_pcs_apply_cdr_pr_idac(priv, index,
								  cdr_pr_idac_tmp);
			fl_out_diff_tmp = abs_diff(fl_out_tmp, target_fl_out);
			if (fl_out_diff_tmp < fl_out_diff) {
				fl_out = fl_out_tmp;
				fl_out_diff = fl_out_diff_tmp;
				cdr_pr_idac = cdr_pr_idac_tmp;
			}
		}
	}
	dev_dbg(priv->dev, "Selected CDR Pr Idac: %x Fl Out: %x\n", cdr_pr_idac, fl_out);
	if (fl_out_diff > 100)
		dev_dbg(priv->dev, "Fl Out is %d far from target %d on intermediate calibration.\n",
			fl_out_diff, target_fl_out);

	/* Setup Load Band */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CDR_PR_INJ_FORCE_OFF], 0x0);

	/* Disable force of LPF C previously enabled */
	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_LPF_C_EN,
			  AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_LPF_C_EN);

	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_IDAC,
			  AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_IDAC);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_RX_FLL_B,
			AIROHA_PCS_PMA_LOAD_EN);

	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_RX_FLL_1,
			   AIROHA_PCS_PMA_LPATH_IDAC,
			   FIELD_PREP(AIROHA_PCS_PMA_LPATH_IDAC, cdr_pr_idac));

	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_PIEYE_PWDB,
			  AIROHA_PCS_PMA_FORCE_DA_CDR_PR_PWDB);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_PIEYE_PWDB,
			AIROHA_PCS_PMA_FORCE_DA_CDR_PR_PWDB);

	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_PR_PIEYE_PWDB,
			  AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_PR_PWDB);

	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_SW_RST_SET,
			  AIROHA_PCS_PMA_SW_REF_RST_N);

	usleep_range(100, 200);
}

/* This is used to both calibrate and lock to signal (after a previous
 * calibration) after a global reset.
 */
static void an7581_pcs_cdr_reset(struct airoha_pcs_priv *priv, int index,
				 phy_interface_t interface, bool calibrate)
{
	struct regmap *pcs_pma = priv->pcs_pma[index];

	/* Setup LPF L2D force and disable */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_LPF_LCK_2DATA,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_LPF_LCK2DATA |
			   AIROHA_PCS_PMA_FORCE_DA_CDR_LPF_LCK2DATA,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_LPF_LCK2DATA);

	/* Calibrate IDAC and setup Load Band */
	if (calibrate)
		an7581_pcs_rx_prcal(priv, index, interface);

	/* Setup LPF RSTB force and disable */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_LPF_LCK_2DATA,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_LPF_RSTB |
			   AIROHA_PCS_PMA_FORCE_DA_CDR_LPF_RSTB,
			   AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_LPF_RSTB);

	usleep_range(700, 1000);

	/* Force Enable LPF RSTB */
	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_LPF_LCK_2DATA,
			AIROHA_PCS_PMA_FORCE_DA_CDR_LPF_RSTB);

	usleep_range(100, 200);

	/* Force Enable LPF L2D */
	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_LPF_LCK_2DATA,
			AIROHA_PCS_PMA_FORCE_DA_CDR_LPF_LCK2DATA);

	/* Disable LPF RSTB force bit */
	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_LPF_LCK_2DATA,
			  AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_LPF_RSTB);

	/* Disable LPF L2D force bit */
	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_PXP_CDR_LPF_LCK_2DATA,
			  AIROHA_PCS_PMA_FORCE_SEL_DA_CDR_LPF_LCK2DATA);
}

static int an7581_pcs_phya_bringup(struct airoha_pcs_priv *priv,
				   int index, phy_interface_t interface)
{
	struct regmap *pcs_pma = priv->pcs_pma[index];
	int calibration_try = 0;
	u32 val = 0;

	an7581_pcs_tx_bringup(priv, index, interface);
	an7581_pcs_rx_bringup(priv, index, interface);

	usleep_range(100, 200);

retry_calibration:
	an7581_pcs_cdr_reset(priv, index, interface, priv->manual_rx_calib);

	/* Global reset clear */
	regmap_update_bits(pcs_pma, AIROHA_PCS_PMA_SW_RST_SET,
			   AIROHA_PCS_PMA_SW_HSG_RXPCS_RST_N |
			   AIROHA_PCS_PMA_SW_HSG_TXPCS_RST_N |
			   AIROHA_PCS_PMA_SW_XFI_RXPCS_BIST_RST_N |
			   AIROHA_PCS_PMA_SW_XFI_RXPCS_RST_N |
			   AIROHA_PCS_PMA_SW_XFI_TXPCS_RST_N |
			   AIROHA_PCS_PMA_SW_TX_FIFO_RST_N |
			   AIROHA_PCS_PMA_SW_REF_RST_N |
			   AIROHA_PCS_PMA_SW_ALLPCS_RST_N |
			   AIROHA_PCS_PMA_SW_PMA_RST_N |
			   AIROHA_PCS_PMA_SW_TX_RST_N |
			   AIROHA_PCS_PMA_SW_RX_RST_N |
			   AIROHA_PCS_PMA_SW_RX_FIFO_RST_N,
			   AIROHA_PCS_PMA_SW_REF_RST_N);

	usleep_range(100, 200);

	/* Global reset */
	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_SW_RST_SET,
			AIROHA_PCS_PMA_SW_HSG_RXPCS_RST_N |
			AIROHA_PCS_PMA_SW_HSG_TXPCS_RST_N |
			AIROHA_PCS_PMA_SW_XFI_RXPCS_BIST_RST_N |
			AIROHA_PCS_PMA_SW_XFI_RXPCS_RST_N |
			AIROHA_PCS_PMA_SW_XFI_TXPCS_RST_N |
			AIROHA_PCS_PMA_SW_TX_FIFO_RST_N |
			AIROHA_PCS_PMA_SW_REF_RST_N |
			AIROHA_PCS_PMA_SW_ALLPCS_RST_N |
			AIROHA_PCS_PMA_SW_PMA_RST_N |
			AIROHA_PCS_PMA_SW_TX_RST_N |
			AIROHA_PCS_PMA_SW_RX_RST_N |
			AIROHA_PCS_PMA_SW_RX_FIFO_RST_N);

	usleep_range(5000, 7000);

	an7581_pcs_cdr_reset(priv, index, interface, false);

	/* Manual RX calibration is required only for SoC before E2
	 * revision. E2+ SoC autocalibrate RX and only CDR reset is needed.
	 */
	if (!priv->manual_rx_calib)
		return 0;

	/* It was discovered that after a global reset and auto mode gets
	 * actually enabled, the fl_out from calibration might change and
	 * might deviates a lot from the expected value it was calibrated for.
	 * To correctly work, the PCS FreqDet module needs to Lock to the fl_out
	 * (frequency level output) or no signal can correctly be transmitted.
	 * This is detected by checking the FreqDet module Lock bit.
	 *
	 * If it's detected that the FreqDet module is not locked, retry
	 * calibration. From observation on real hardware with a 10g SFP module,
	 * it required a maximum of an additional calibration to actually make
	 * the FreqDet module to lock. Try 10 times before failing to handle
	 * really strange case.
	 */
	regmap_read(pcs_pma, AIROHA_PCS_PMA_RX_FREQDET, &val);
	if (!(val & AIROHA_PCS_PMA_FBCK_LOCK)) {
		if (calibration_try > AIROHA_PCS_MAX_CALIBRATION_TRY) {
			dev_err(priv->dev, "No FBCK Lock from FreqDet module after %d calibration try. PCS won't work.\n",
				AIROHA_PCS_MAX_CALIBRATION_TRY);
			return -EIO;
		}

		calibration_try++;

		dev_dbg(priv->dev, "No FBCK Lock from FreqDet module, retry calibration.\n");
		goto retry_calibration;
	}

	return 0;
}

static void an7581_pcs_pll_bringup(struct airoha_pcs_priv *priv,
				   int index, phy_interface_t interface)
{
	an7581_pcs_jcpll_bringup(priv, index, interface);

	usleep_range(200, 300);

	an7581_pcs_txpll_bringup(priv, index, interface);

	usleep_range(200, 300);
}

int an7581_pcs_bringup(struct airoha_pcs_priv *priv, int index,
		       phy_interface_t interface)
{
	struct regmap_field **pcs_ana_fields = priv->pcs_ana_fields[index];

	/* Enable Analog Common Lane */
	regmap_field_write(pcs_ana_fields[AN7581_PCS_CMN_EN], 0x1);

	/* Setup PLL */
	an7581_pcs_pll_bringup(priv, index, interface);

	msleep(100);

	/* Setup PHYA */
	return an7581_pcs_phya_bringup(priv, index, interface);
}

int an7581_pcs_usb_bringup(struct airoha_pcs_priv *priv,
			   int index, phy_interface_t interface)
{
	int ret;

	ret = phy_set_mode_ext(priv->phy, PHY_MODE_ETHERNET, interface);
	if (ret)
		return ret;

	if (interface == PHY_INTERFACE_MODE_2500BASEX) {
		regmap_update_bits(priv->pcs_ana, AIROHA_PCS_HSGMII_ANA_SGMII_PHYA_8,
				   AIROHA_PCS_HSGMII_ANA_SSUSB_CDR_BICLTR |
				   AIROHA_PCS_HSGMII_ANA_SSUSB_CDR_BICLTD1 |
				   AIROHA_PCS_HSGMII_ANA_SSUSB_CDR_BICLTD0,
				   FIELD_PREP(AIROHA_PCS_HSGMII_ANA_SSUSB_CDR_BICLTR, 0xf) |
				   FIELD_PREP(AIROHA_PCS_HSGMII_ANA_SSUSB_CDR_BICLTD1, 0xc) |
				   FIELD_PREP(AIROHA_PCS_HSGMII_ANA_SSUSB_CDR_BICLTD0, 0x3));

		regmap_set_bits(priv->pcs_ana, AIROHA_PCS_HSGMII_ANA_SGMII_PHYA_6,
				AIROHA_PCS_HSGMII_ANA_FORCE_CDR_BIC);
	} else {
		regmap_clear_bits(priv->pcs_ana, AIROHA_PCS_HSGMII_ANA_SGMII_PHYA_6,
				  AIROHA_PCS_HSGMII_ANA_FORCE_CDR_BIC);
	}

	regmap_update_bits(priv->pcs_ana, AIROHA_PCS_HSGMII_ANA_SGMII_PHYA_26,
			   AIROHA_PCS_HSGMII_ANA_SSUSB_LN0_CDR_RST_DLY,
			   AIROHA_PCS_HSGMII_ANA_SSUSB_LN0_CDR_RST_DLY_32);

	regmap_clear_bits(priv->pcs_ana, AIROHA_PCS_HSGMII_ANA_SGMII_PHYA_24,
			  AIROHA_PCS_HSGMII_ANA_SSUSB_LN0_CDR_RESERVE);

	regmap_update_bits(priv->pcs_ana, AIROHA_PCS_HSGMII_ANA_SGMII_PHYA_18,
			   AIROHA_PCS_HSGMII_ANA_SSUSB_BG_DIV,
			   FIELD_PREP(AIROHA_PCS_HSGMII_ANA_SSUSB_BG_DIV, 0x1));

	regmap_update_bits(priv->pcs_ana, AIROHA_PCS_HSGMII_ANA_SGMII_PHYA_19,
			   AIROHA_PCS_HSGMII_ANA_SSUSB_XTAL_TOP_RESERVE,
			   FIELD_PREP(AIROHA_PCS_HSGMII_ANA_SSUSB_XTAL_TOP_RESERVE,
				      FIELD_PREP(AIROHA_PCS_HSGMII_ANA_SSUSB_XTAL_TOP_RESERVE_HV,
						 AIROHA_PCS_HSGMII_ANA_SSUSB_XTAL_TOP_RESERVE_NS_MONPLL_CK)));

	if (interface == PHY_INTERFACE_MODE_2500BASEX)
		regmap_update_bits(priv->pcs_ana, AIROHA_PCS_HSGMII_ANA_SGMII_PHYA_11,
				   AIROHA_PCS_HSGMII_ANA_TPHY_SPEED,
				   AIROHA_PCS_HSGMII_ANA_TPHY_SPEED_HSGMII);
	else
		regmap_update_bits(priv->pcs_ana, AIROHA_PCS_HSGMII_ANA_SGMII_PHYA_11,
				   AIROHA_PCS_HSGMII_ANA_TPHY_SPEED,
				   AIROHA_PCS_HSGMII_ANA_TPHY_SPEED_SGMII);

	return 0;
}

void an7581_pcs_phya_link_up(struct airoha_pcs_priv *priv, int index)
{
	struct regmap *pcs_pma = priv->pcs_pma[index];

	/* Reset TXPCS on link up */
	regmap_clear_bits(pcs_pma, AIROHA_PCS_PMA_SW_RST_SET,
			  AIROHA_PCS_PMA_SW_HSG_TXPCS_RST_N);

	usleep_range(100, 200);

	regmap_set_bits(pcs_pma, AIROHA_PCS_PMA_SW_RST_SET,
			AIROHA_PCS_PMA_SW_HSG_TXPCS_RST_N);
}

static int __an7581_pcs_alloc_regmap_fields(struct airoha_pcs_priv *priv, int index,
					    const struct reg_field *fields)
{
	struct device *dev = priv->dev;
	int i;

	priv->pcs_ana_fields[index] = devm_kcalloc(dev, AN7581_PCS_FIELDS_MAX,
						   sizeof(*priv->pcs_ana_fields[index]),
						   GFP_KERNEL);
	if (!priv->pcs_ana_fields[index])
		return -ENOMEM;

	for (i = 0; i < AN7581_PCS_FIELDS_MAX; i++) {
		struct regmap_field *field;

		field = devm_regmap_field_alloc(dev, priv->pcs_ana,
						fields[i]);
		if (IS_ERR(field))
			return PTR_ERR(field);

		priv->pcs_ana_fields[index][i] = field;
	}

	return 0;
}

int an7581_pcs_alloc_regmap_fields(struct airoha_pcs_priv *priv)
{
	return __an7581_pcs_alloc_regmap_fields(priv, 0, an7581_pcs_fields);
}

int an7581_pcs_pcie_alloc_regmap_fields(struct airoha_pcs_priv *priv)
{
	int ret;

	ret = __an7581_pcs_alloc_regmap_fields(priv, 0, an7581_pcs_pcie0_fields);
	if (ret)
		return ret;

	return __an7581_pcs_alloc_regmap_fields(priv, 1, an7581_pcs_pcie1_fields);
}

static bool an7581_pcs_have_rx_signal(struct airoha_pcs_priv *priv, int index)
{
	struct regmap *pcs_pma = priv->pcs_pma[index];
	unsigned int count = 0;
	u32 val = 0;
	int i;

	regmap_write(pcs_pma, AIROHA_PCS_PMA_DIG_RESERVE_0,
		     AIROHA_PCS_TRIGGER_RX_SIDGET_SCAN);

	/* Scan 6 times for RX sigdet module to detect RX signal */
	for (i = 0; i < AIROHA_PCS_MAX_RX_SIGDET_TRY; i++) {
		regmap_read(pcs_pma, AIROHA_PCS_PMA_DIG_RO_RESERVE_2,
			    &val);
		if (val & AIROHA_PCS_RX_SIGDET)
			count++;
	}

	/* Consider signal presence if we detect signal at least 4 times */
	return count >= AIROHA_PCS_MAX_RX_SIGDET_PRESENCE_CNT;
}

int an7581_pcs_rxlock_workaround(struct airoha_pcs_priv *priv, int index)
{
	struct airoha_pcs_maps *maps = &priv->maps[index];
	u32 val = 0;

	/* Check if PCS is UP or Down */
	regmap_read(maps->usxgmii_pcs, AIROHA_PCS_USXGMII_PCS_STUS_1, &val);
	if (val & AIROHA_PCS_USXGMII_PCS_RX_LINK_STATUS_UP)
		return 0;

	/* Validate if this is consistent with RX SigDet module */
	if (!an7581_pcs_have_rx_signal(priv, index))
		return 0;

	/* If PCS is down but RX SigDet module detected signal,
	 * trigger CDR reset.
	 */
	an7581_pcs_cdr_reset(priv, index, PHY_INTERFACE_MODE_NA, false);

	/* Report there is an error with Link Detection and we
	 * should test again later.
	 */
	return -EINVAL;
}
