obj-$(CONFIG_NET_DSA_MV88E6060) += mv88e6060.o
obj-$(CONFIG_NET_DSA_BCM_SF2)	+= bcm_sf2.o
obj-$(CONFIG_NET_DSA_QCA8K)	+= qca8k.o
obj-$(CONFIG_NET_DSA_MT7530) += mt7530.o
obj-y				+= b53/
obj-y				+= mv88e6xxx/
